### ISSUE TITLE
The 0.7.0 version uses zookeeper 3.5.5 to do registration center error

### ISSUE THREAD

**Issue by MrLiuFang** [apache/incubator-seata#1293]
下载0.7.0版本 解压后 修改
registry {
  #file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "zk"

config {
  #file、nacos 、apollo、zk、consul、etcd3
  type = "zk"

zookeeper 版本：3.5.5

启动后报：
2019-07-12 16:38:37.083 INFO [main-SendThread(localhost:2181)]org.apache.zookeeper.ClientCnxn.logStartConnect:1025 -Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2019-07-12 16:38:37.117 INFO [main-SendThread(localhost:2181)]org.apache.zookeeper.ClientCnxn.primeConnection:879 -Socket connection established to localhost/127.0.0.1:2181, initiating session
2019-07-12 16:38:37.121 INFO [main-SendThread(localhost:2181)]org.apache.zookeeper.ClientCnxn.onConnected:1299 -Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x10000667c520001, negotiated timeout = 6000
2019-07-12 16:38:37.122 INFO [main-EventThread]org.I0Itec.zkclient.ZkClient.processStateChanged:713 -zookeeper state changed (SyncConnected)
2019-07-12 16:38:37.131 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig metrics.enabled is error or timeout,return defaultValue false
2019-07-12 16:38:37.148 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.boss-thread-prefix is error or timeout,return defaultValue null
2019-07-12 16:38:37.149 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.worker-thread-prefix is error or timeout,return defaultValue null
2019-07-12 16:38:37.150 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.share-boss-worker is error or timeout,return defaultValue false
2019-07-12 16:38:37.151 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.type is error or timeout,return defaultValue TCP
2019-07-12 16:38:37.151 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.worker-thread-size is error or timeout,return defaultValue null
2019-07-12 16:38:37.154 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.server is error or timeout,return defaultValue NIO
2019-07-12 16:38:37.157 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.heartbeat is error or timeout,return defaultValue false
2019-07-12 16:38:37.186 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.boss-thread-size is error or timeout,return defaultValue 1
2019-07-12 16:38:37.187 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.boss-thread-prefix is error or timeout,return defaultValue NettyBoss
2019-07-12 16:38:37.187 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.boss-thread-size is error or timeout,return defaultValue 1
2019-07-12 16:38:37.202 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig transport.thread-factory.worker-thread-prefix is error or timeout,return defaultValue NettyServerNIOWorker
2019-07-12 16:38:37.206 ERROR[main]io.seata.config.zk.ZookeeperConfiguration.getConfig:103 -getConfig store.file.dir is error or timeout,return defaultValue null
Exception in thread "main" io.seata.common.exception.StoreException: the {store.file.dir} is empty.
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:102)
	at io.seata.server.Server.main(Server.java:68)

**Comment by cmonkey** [comment]
在服务初始化的时候，会调用SessionHolder.init , 在不通过-m 传参的情况下，默认mode 是file

而当前Config 提供者是zk , 所以会去zk 读取/config/store.file.dir 节点的值，所以你需要设置znode 的值

**Comment by slievrly** [comment]
@cmonkey Can you help everyone fix this problem?

**Comment by cmonkey** [comment]
pr 1329

**Comment by niejian** [comment]
> /config/store.file.dir
版本是0.7.1，在zk上添加了/config/store.file.dir 节点还是爆同样的错误。

**Comment by cmonkey** [comment]
> > /config/store.file.dir
> > 版本是0.7.1，在zk上添加了/config/store.file.dir 节点还是爆同样的错误。

develop 分支修复的

**Comment by luojiachengaccp** [comment]
seata版本为0.8.1还是有这种错误提示~
