### ISSUE TITLE
Using jrebel makes GlobalTransactionScanner throw exception.

### ISSUE THREAD

**Issue by wang-liqiang** [apache/incubator-seata#1458]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
I'm using jrebel to reloading class changes, but the GlobalTransactionScanner throw java.lang.NoSuchFieldException: advised while start the application.

### Ⅱ. Describe what happened
Here is the stack trace(Omitted non key parts):

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'logOperationDao': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:119)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1654)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1174)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:327)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:581)
	... 90 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:245)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:304)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1836)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:116)
	... 98 common frames omitted
Caused by: java.lang.NoSuchFieldException: advised
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at io.seata.spring.util.SpringProxyUtils.getAdvisedSupport(SpringProxyUtils.java:98)
	at io.seata.spring.util.SpringProxyUtils.findTargetClass(SpringProxyUtils.java:42)
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:216)
```
Using jrebel:
![image](https://user-images.githubusercontent.com/37055157/62992515-5572e900-be86-11e9-8708-524ffc6b8a61.png)
Not using jrebel:
![image](https://user-images.githubusercontent.com/37055157/62992897-d67eb000-be87-11e9-9ae7-3b384b90141e.png)
I think this may be what the problem is, jrebel will create a proxy for the spring bean, that affect the method getAdvisedSupport to get actual proxy which contians "advised" field. Maybe  other frameworks who creates proxy will cuase the same exception.

### Ⅵ. Environment:

- JDK version :1.8
- OS :windows 10
- Others:

**Comment by MarkusPunnar** [comment]
Hello!

Could you send an email with all this information to support@jrebel.com so we could take a look at what exactly is going wrong?

Thanks

**Comment by wang-liqiang** [comment]
> Hello!
> 
> Could you send an email with all this information to [support@jrebel.com](mailto:support@jrebel.com) so we could take a look at what exactly is going wrong?
> 
> Thanks

@MarkusPunnar I don't think this is the problem of jrebel, proxy is a very common way to to some work, if seata only try to look up it's own proxy in super class directly, other framework or tools which using proxy may cuase the same exception.

**Comment by lzxgyh** [comment]
I encountered the same error  when I start application with JRebel

Caused by: java.lang.NoSuchFieldException: advised

Here is the full stack trace 

```java
[2020-06-02 18:15:40.419 +0800] [ebaogi] [DEV] [plan] [25430] [main] [] [] [] [] [] [ERROR] org.springframework.boot.SpringApplication 858 :Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'notificationRestful': Unsatisfied dependency expressed through field 'productReceiveRestful'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'productReceiveRestful': Unsatisfied dependency expressed through field 'mediaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mediaServiceImpl': Unsatisfied dependency expressed through field 'documentReceptionRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentReceptionRepository': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:40002)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:41008)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.ebao.unicorn.platform.lib.LibAdapterGatewayApplication.main(LibAdapterGatewayApplication.java:14)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'productReceiveRestful': Unsatisfied dependency expressed through field 'mediaService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mediaServiceImpl': Unsatisfied dependency expressed through field 'documentReceptionRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentReceptionRepository': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 21 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mediaServiceImpl': Unsatisfied dependency expressed through field 'documentReceptionRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentReceptionRepository': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 34 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentReceptionRepository': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:119)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1674)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1249)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:330)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 47 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: advised
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:249)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:429)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1920)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:116)
	... 55 common frames omitted
Caused by: java.lang.NoSuchFieldException: advised
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at io.seata.spring.util.SpringProxyUtils.getAdvisedSupport(SpringProxyUtils.java:99)
	at io.seata.spring.util.SpringProxyUtils.findTargetClass(SpringProxyUtils.java:42)
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:220)
	... 59 common frames omitted

Debug with JRebel
<img width="957" alt="image-20200602181446111" src="https://user-images.githubusercontent.com/18474120/83510155-1d18c600-a4ff-11ea-96bf-ccc2598f136f.png">

Debug without JRebel
<img width="1140" alt="image-20200602182204777" src="https://user-images.githubusercontent.com/18474120/83510225-3de11b80-a4ff-11ea-97f7-12e7f1bc0134.png">

**Comment by cay914** [comment]
这个问题，还没有解决吗？

**Comment by cay914** [comment]
@slievrly io.seata.spring.util.SpringProxyUtils#getAdvisedSupport这个方法拦截了jrebel的aop方法。
请看下处理这个问题

![image](https://user-images.githubusercontent.com/6037435/90149588-3b305b80-ddb7-11ea-8d43-96e7f8001ec6.png)

**Comment by DongJigong** [comment]
So am I. This problem hasn't resolved yet.

**Comment by l97069947** [comment]
这个问题还没解决吗?同样的问题?有没有可能通过排除seata的aop的扫描范围来解决这个问题

**Comment by Martin-Mo** [comment]
可以通过AOP拦截GlobalTransactionScanner里的wrapIfNecessary，不过需要修改的代码比较多。最理想的是修改下面两行：

Class<?> serviceInterface = SpringProxyUtils.findTargetClass(bean);

Class<?>[] interfacesIfJdk = SpringProxyUtils.findInterfaces(bean);

不过此处不在相对独立的Bean方法里，AOP拦截不了。。。希望@slievrly 能提供个解决方案。谢谢

**Comment by fangzhengjin** [comment]
还是没有解决....

**Comment by liuzhen9327** [comment]
![image](https://github.com/seata/seata/assets/7447842/f59e54f7-8865-4e3c-a9cb-e0c305840813)
可以在本地开发环境禁用掉seata就能用jrebel起来了，逻辑代码不用改动

**Comment by charlieDJ** [comment]
> ![image](https://private-user-images.githubusercontent.com/7447842/261980140-f59e54f7-8865-4e3c-a9cb-e0c305840813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MzY3NTIsIm5iZiI6MTcxMDgzNjQ1MiwicGF0aCI6Ii83NDQ3ODQyLzI2MTk4MDE0MC1mNTllNTRmNy04ODY1LTRlM2MtYTljYi1lMGMzMDU4NDA4MTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDgyMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRlYjU3NTU2OTRkNTI3OTk0ZDYyMzljYWVmZDZjZjJjY2VlM2I1NzMzN2I3OGRkNjc2YjlkZmZiZDdiZTBjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XK-2I3O9BPSaVdHQf8EvYC9h5MTkMhJUcOuno8vL9y8) 可以在本地开发环境禁用掉seata就能用jrebel起来了，逻辑代码不用改动

我在application.yaml文件中改动后，项目能启动了。再观察观察。

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/pull/2852
