### ISSUE TITLE
seata1.4.2中io.seata.spring.util.SpringProxyUtils#findTargetClass相关的代码影响了spring security oauth2的bean初始化

### ISSUE THREAD

**Issue by yougecn** [apache/incubator-seata#3709]
seata1.4.2中io.seata.spring.util.SpringProxyUtils#findTargetClass相关的代码影响了spring security oauth2的bean初始化
spring security oauth2中用到了RequestScope作用域的bean
使用1.4.1的话系统启动正常
详细堆栈如下
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'oauth2ClientContext': Post-processing of FactoryBean's singleton object failed; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:119) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1828) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1265) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 69 common frames omitted
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:287) ~[seata-all-1.4.2.jar:1.4.2]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:299) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1937) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:116) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 77 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:372) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at io.seata.spring.util.SpringProxyUtils.findTargetClass(SpringProxyUtils.java:51) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:256) ~[seata-all-1.4.2.jar:1.4.2]
	... 81 common frames omitted
Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.context.request.SessionScope.get(SessionScope.java:55) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:360) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 85 common frames omitted

**Comment by ls9527** [comment]
我来处理整合 spring security oauth2 初始化的问题

**Comment by ls9527** [comment]
在1.4.1 之前，对于TargetSource这个对象， 认为就是静态对象，所以直接取的targetSource.getTargetClass()

在1.4.2版本，又完全认为是一个动态对象

而你这里的问题就是获取一个被代理的动态对象时，实际上是不能获取这个对象的， 只能获取这个对象的类型

```
// 省略无关代码段
@Configuration
public class OAuth2ClientConfiguration {
       // spring 要创建这个对象，  创建后被seata的SpringProxyUtils感知
       //  实际上这是一个动态对象，是不能在启动阶段拿这个值的
       // 这里定义的方式是：  ScopedProxyFactoryBean->SimpleBeanTargetSource->当前对象
	@Bean
	@Scope(value = "request", proxyMode = ScopedProxyMode.INTERFACES)
	protected AccessTokenRequest accessTokenRequest(@Value("#{request.parameterMap}")
	Map<String, String[]> parameters, @Value("#{request.getAttribute('currentUri')}")
	String currentUri) {
	}
	@Configuration
	protected static class OAuth2ClientContextConfiguration {
		// 1. spring 要注入这个对象
		@Resource
		@Qualifier("accessTokenRequest")
		private AccessTokenRequest accessTokenRequest;
	}
}

```

我认为做个兼容就行了

```
  public static Class<?> findTargetClass(Object proxy) throws Exception {
        if (proxy == null) {
            return null;
        }
// 比如说把这里加一个条件判断，静态就可以获取对象并且递归获取具体的类型。  
// 动态的话，是万万不能获取对象的
        if (AopUtils.isAopProxy(proxy) && proxy instanceof Advised) {
            final TargetSource targetSource = ((Advised) proxy).getTargetSource();
// 对于这个issue的情况， 直接取class
            if (!targetSource.isStatic()) {
                return targetSource.getTargetClass();
            }
// 支持静态域的层次情况
            return findTargetClass(targetSource.getTarget());
        }
        return proxy.getClass();
    }
```

在多说两句额外的话：
在spring-aop中， 通过 ProxyFactory.getProxy->CgLibAopProxy.getCallbacks里面也有同样的判断
静态就可以取具体对象做静态拦截，  动态的话，就不能获取对象
```
// CgLibAopProxy.getCallbacks 的植入方式
		boolean isStatic = this.advised.getTargetSource().isStatic();
	     if (exposeProxy) {
			targetInterceptor = (isStatic ?
					new StaticUnadvisedExposedInterceptor(this.advised.getTargetSource().getTarget()) :
					new DynamicUnadvisedExposedInterceptor(this.advised.getTargetSource()));
		}
		else {
			targetInterceptor = (isStatic ?
					new StaticUnadvisedInterceptor(this.advised.getTargetSource().getTarget()) :
					new DynamicUnadvisedInterceptor(this.advised.getTargetSource()));
		}
```

**Comment by yougecn** [comment]
io.seata.spring.util.SpringProxyUtils#findTargetClass 中加了targetSource.isStatic()判断后可以解决这个问题，已经测试验证过了，期待seata下个小版本中修复这个问题。
谢谢！

**Comment by chapterBegin** [comment]
为什么要单例的bean里面注入scope是session的bean？

**Comment by zhoushenn** [comment]
啥时候合并发布下这个特性... 目前1.4.2依然存在这个问题= =

**Comment by kit101** [comment]
@zhoushenn 
用这个PR #3716 的代码新建一个同名类覆盖seata的类就可以了，临时解决一下了。
[SpringProxyUtils.java](https://github.com/ls9527/seata/blob/ddaeaf7678368a8fad0f8c579446ca8ecde2b683/spring/src/main/java/io/seata/spring/util/SpringProxyUtils.java)
