### ISSUE TITLE
The AdapterSpringSeataInterceptor's order '2147483647' is lower or equals than TransactionInterceptor's order '2147483647' , reset AdapterSpringSeataInterceptor's order to higher order '2147483646'.

### ISSUE THREAD

**Issue by Self-revolution** [apache/incubator-seata#6138]
WARN i.s.s.annotation.GlobalTransactionScanner: The AdapterSpringSeataInterceptor's order '2147483647' is lower or equals than TransactionInterceptor's order '2147483647' , reset AdapterSpringSeataInterceptor's order to higher order '2147483646'.

The warning appeared when I upgrade to seata 2.0.0, and my application has error when using Global Transaction.

**Comment by wangliang181230** [comment]
What is the version of seata?

**Comment by Self-revolution** [comment]
> What is the version of seata?

2.0.0 as I mentioned. My application can run when using 1.8.0.

**Comment by wangliang181230** [comment]
The order `2147483647` configured by yourself?
I remember the default value is `-2147482648`.

**Comment by Self-revolution** [comment]
I configured my seata using demo properties in https://github.com/seata/seata/blob/v2.0.0/script/config-center/config.txt , store by mysql.
The file gave two orders: `client.rm.tccActionInterceptorOrder=-2147482648`, `client.tm.interceptorOrder=-2147482648`, and no `2147483647` is configured.

**Comment by wangliang181230** [comment]
I saw that the relevant code has been modified by someone, it seems to be a bug. I'll go take a look later.

**Comment by Self-revolution** [comment]
Okay, thank you.

**Comment by wangliang181230** [comment]
Rest assured, this bug does not affect usage.

**Comment by wangliang181230** [comment]
> WARN i.s.s.annotation.GlobalTransactionScanner: The AdapterSpringSeataInterceptor's order '2147483647' is lower or equals than TransactionInterceptor's order '2147483647' , reset AdapterSpringSeataInterceptor's order to higher order '2147483646'.
> 
> The warning appeared when I upgrade to seata 2.0.0, and my application has error when using Global Transaction.

This warning does not affect usage. What exception was thrown in your application?

**Comment by Self-revolution** [comment]
```java
java.lang.RuntimeException: try to proceed invocation error
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:59) ~[seata-all-2.0.0.jar!/:2.0.0]
	at io.seata.integration.tx.api.interceptor.handler.AbstractProxyInvocationHandler.invoke(AbstractProxyInvocationHandler.java:33) ~[seata-all-2.0.0.jar!/:2.0.0]
	at io.seata.spring.annotation.AdapterSpringSeataInterceptor.invoke(AdapterSpringSeataInterceptor.java:45) ~[seata-all-2.0.0.jar!/:2.0.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at com.holo.wcs.service.device.instance.device.handler.DeviceHandler$$SpringCGLIB$$0.deviceMethodExecute(<generated>) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.device.device.domain.StackerDismantler.poll(StackerDismantler.java:62) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.manager.DeviceManager.poll(DeviceManager.java:241) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.manager.DeviceManager.lambda$poll$3(DeviceManager.java:224) ~[classes!/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.holo.wcs.service.device.instance.device.ex.DeviceExWrapperException
	at com.holo.wcs.service.device.instance.device.handler.DeviceHandler.deviceMethodExecute(DeviceHandler.java:69) ~[classes!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:57) ~[seata-all-2.0.0.jar!/:2.0.0]
	... 12 more
```

**Comment by wangliang181230** [comment]
> ```java
> java.lang.RuntimeException: try to proceed invocation error
> 	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:59) ~[seata-all-2.0.0.jar!/:2.0.0]
> 	at io.seata.integration.tx.api.interceptor.handler.AbstractProxyInvocationHandler.invoke(AbstractProxyInvocationHandler.java:33) ~[seata-all-2.0.0.jar!/:2.0.0]
> 	at io.seata.spring.annotation.AdapterSpringSeataInterceptor.invoke(AdapterSpringSeataInterceptor.java:45) ~[seata-all-2.0.0.jar!/:2.0.0]
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at com.holo.wcs.service.device.instance.device.handler.DeviceHandler$$SpringCGLIB$$0.deviceMethodExecute(<generated>) ~[classes!/:?]
> 	at com.holo.wcs.service.device.instance.device.device.domain.StackerDismantler.poll(StackerDismantler.java:62) ~[classes!/:?]
> 	at com.holo.wcs.service.device.instance.manager.DeviceManager.poll(DeviceManager.java:241) ~[classes!/:?]
> 	at com.holo.wcs.service.device.instance.manager.DeviceManager.lambda$poll$3(DeviceManager.java:224) ~[classes!/:?]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> Caused by: com.holo.wcs.service.device.instance.device.ex.DeviceExWrapperException
> 	at com.holo.wcs.service.device.instance.device.handler.DeviceHandler.deviceMethodExecute(DeviceHandler.java:69) ~[classes!/:?]
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
> 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
> 	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:57) ~[seata-all-2.0.0.jar!/:2.0.0]
> 	... 12 more
> ```

What is the `DeviceExWrapperException`?
This doesn't seem to be an exception caused by seata.

**Comment by Self-revolution** [comment]
The error didn't appear when I change seata version to 1.8.0. `DeviceExWrapperException` is an Exception threw by myself, I romoved it and simplified my code and try to find the reason. I found the error occurred in `DeviceHandler` which has a function with `@GlobalTransactional`. The simplfied class is given as follow:
```java
@Service
public class DeviceHandler {

  public void deviceMethodExecute(Predicate<Locator> method, Locator locator) {
    method.test(locator);
  }

  @GlobalTransactional
  public void lockConnectorListAndInsertTask() {
    ...
  }

}
```
The error message is shown as follow:
```java
java.lang.RuntimeException: try to proceed invocation error
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:59) ~[seata-all-2.0.0.jar!/:2.0.0]
	at io.seata.integration.tx.api.interceptor.handler.AbstractProxyInvocationHandler.invoke(AbstractProxyInvocationHandler.java:33) ~[seata-all-2.0.0.jar!/:2.0.0]
	at io.seata.spring.annotation.AdapterSpringSeataInterceptor.invoke(AdapterSpringSeataInterceptor.java:45) ~[seata-all-2.0.0.jar!/:2.0.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at com.holo.wcs.service.device.instance.device.handler.DeviceHandler$$SpringCGLIB$$0.deviceMethodExecute(<generated>) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.device.device.domain.StackerDismantler.poll(StackerDismantler.java:62) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.manager.DeviceManager.poll(DeviceManager.java:238) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.manager.DeviceManager.lambda$poll$3(DeviceManager.java:224) ~[classes!/:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.holo.wcs.service.device.instance.device.ex.DevicePollReturnException: 设备【STACKER_DISMANTLER_SS_03_013】的库位【SS-03-013】正在等待最底层容器的扫码结果
	at com.holo.wcs.service.device.instance.device.device.domain.StackerDismantler.inputContainer(StackerDismantler.java:143) ~[classes!/:?]
	at com.holo.wcs.service.device.instance.device.handler.DeviceHandler.deviceMethodExecute(DeviceHandler.java:65) ~[classes!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.1.jar!/:6.1.1]
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:57) ~[seata-all-2.0.0.jar!/:2.0.0]
	... 12 more
```
I threw `DevicePollReturnException` when excuting `method.test(locator);`, and the error should be thrown directly to the caller. But it was warpped by `java.lang.RuntimeException: try to proceed invocation error`. The changed type of exception influenced my judgment. This doesn't happen when using seata 1.8.0.

**Comment by funky-eyes** [comment]
你说的异常是属于标题所说的问题之外的问题了，它将在seata 2.1.0或者2.0.1版本中被修复
The exception you mentioned is in addition to the problem mentioned in the title, and it will be fixed in the seata 2.1.0 or 2.0.1 version

**Comment by funky-eyes** [comment]
https://github.com/seata/seata/pull/6090

**Comment by Self-revolution** [comment]
Well, I don't quite understand why this happens, so I guess the warning in the title might be related to the error. Maybe I misunderstood the message. Anyway, thank you very much for your reply.
