### ISSUE TITLE
seata 在方法中加入@GlobalTransactional,报错 No available service 	at io.seata.core.rpc.netty.AbstractNettyRemotingClient

### ISSUE THREAD

**Issue by zhangchaoyanggit** [apache/incubator-seata#6214]
### Ⅰ. Issue Description
seata 使用的是1.4.2版本, springboot 2.3.2 ,spring-cloud-alibaba-2.2.6.RELEASE springcloud Hoxton.SR9

在业务方法中加入@GlobalTransactional注解后 业务中调用一个feign接口,这个接口通过url实现的, 但是报错
 No available service
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient.loadBalance

在seata文档FQA中有个类似问题 Q: 43 我按照操作配置了一下,并没有走入我的feign拦截器,直接报上面的错误.
 io.seata.common.exception.FrameworkException: No available service
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient.loadBalance(AbstractNettyRemotingClient.java:265) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient.sendSyncRequest(AbstractNettyRemotingClient.java:141) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.tm.DefaultTransactionManager.begin(DefaultTransactionManager.java:53) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:105) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.tm.api.TransactionalTemplate.beginTransaction(TransactionalTemplate.java:215) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:122) ~[seata-all-1.4.2.jar:1.4.2]
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:181) ~[seata-all-1.4.2.jar:1.4.2]

**Comment by funky-eyes** [comment]
配置有问题导致没有读取到server的可用列表
There is a problem with the configuration, resulting in not reading the available list of servers
https://gitee.com/itCjb/spring-cloud-alibaba-seata-demo 
（上述demo内附1.3整合文字版）
The above demo comes with a 1.3 integrated text version

**Comment by zhangchaoyanggit** [comment]
不是的,我这个是走的url调用,不是服务发现,不应该走负载均衡

**Comment by funky-eyes** [comment]
It has nothing to do with your URL call. As long as a transaction occurs, seata has to get the server address. This is seata's load balancing, not your microservices framework.
跟你url调用没关系，只要发生了事务，seata都要去拿到server地址，这是seata的负载均衡，不是你微服务框架的。

**Comment by zhangchaoyanggit** [comment]
已解决感谢

**Comment by eb-zsl** [comment]
我有同样得报错，但是奇怪的点在于偶发，大多数情况下流程是正常得，偶尔发生这个错误，请问我该怎么排查喃

**Comment by eb-zsl** [comment]
> It has nothing to do with your URL call. As long as a transaction occurs, seata has to get the server address. This is seata's load balancing, not your microservices framework. 跟你url调用没关系，只要发生了事务，seata都要去拿到server地址，这是seata的负载均衡，不是你微服务框架的。

您好，我有同样得报错，但是奇怪的点在于偶发，大多数情况下流程是正常得，偶尔发生这个错误，请问我该怎么排查喃

**Comment by minster77** [comment]
> > It has nothing to do with your URL call. As long as a transaction occurs, seata has to get the server address. This is seata's load balancing, not your microservices framework. 跟你url调用没关系，只要发生了事务，seata都要去拿到server地址，这是seata的负载均衡，不是你微服务框架的。
> 
> 您好，我有同样得报错，但是奇怪的点在于偶发，大多数情况下流程是正常得，偶尔发生这个错误，请问我该怎么排查喃

您好，请问你有排查思路吗，我也是偶发的出现这种问题
