### ISSUE TITLE
feign通过url调用 报错No available service 	at io.seata.core.rpc.netty.AbstractNettyRemotingClient.loadBalance(AbstractNettyRemotingClient.java:265) ~[seata-all-1.4.2.jar:1.4.2]

### ISSUE THREAD

**Issue by zhangchaoyanggit** [apache/incubator-seata#6219]
seata 使用的是1.4.2版本, springboot 2.3.2 ,spring-cloud-alibaba-2.2.6.RELEASE springcloud Hoxton.SR9

在业务方法中加入@GlobalTransactional注解后 业务中调用一个第三方接口,通过传递XID方式,在服务另一方设置XID来实现分布式事务   但是通过feign的url调用方式实现,url实现本身走的就不是服务发现,不清楚为什么会触发seata的负载均衡,报了以下错误,
No available service
at io.seata.core.rpc.netty.AbstractNettyRemotingClient.loadBalance

在seata文档FQA中有个类似问题 Q: 43 我按照操作配置了一下,并没有走入我的feign拦截器,直接报上面的错误.
io.seata.common.exception.FrameworkException: No available service
at io.seata.core.rpc.netty.AbstractNettyRemotingClient.loadBalance(AbstractNettyRemotingClient.java:265) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.core.rpc.netty.AbstractNettyRemotingClient.sendSyncRequest(AbstractNettyRemotingClient.java:141) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.tm.DefaultTransactionManager.begin(DefaultTransactionManager.java:53) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:105) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.tm.api.TransactionalTemplate.beginTransaction(TransactionalTemplate.java:215) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:122) ~[seata-all-1.4.2.jar:1.4.2]
at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:181) ~[seata-all-1.4.2.jar:1.4.2]

**Comment by laywin** [comment]
这个错的意思是没能发现seata server, 需要检查一下 seata server的注册的配置 和 客户端 seata的注册配置

This error means that the seata server cannot be found. You need to check the registration configuration of the seata server and the registration configuration of the client seata.

**Comment by zhangchaoyanggit** [comment]
确实,之前改了配置 已解决感谢

**Comment by zhangchaoyanggit** [comment]
已解决,就是配置的问题,sorry
