### ISSUE TITLE
多节点部署seata-server，分布式事务被其他节点提交，导致事务失败。

### ISSUE THREAD

**Issue by xuwei919** [apache/incubator-seata#6229]
Ⅰ. Issue Description
注册中心为nacos，部署两个seata-server，在启动命令中设置多节点参数 -n ,执行分布式事务的业务报错事务已经完成，多节点是否设置是不是没有生效，当前事务已被提交。

io.seata.core.exception.GlobalTransactionException: Could not found global transaction xid = 192.168.171.130:8091:793107603294728461, may be has finished.
        at io.seata.server.coordinator.AbstractCore.assertGlobalSessionNotNull(AbstractCore.java:126) ~[classes!/:1.7.1]
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:76) ~[classes!/:1.7.1]
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:103) ~[classes!/:1.7.1]
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:294) [classes!/:1.7.1]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[classes!/:1.7.1]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[classes!/:1.7.1]
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131) ~[seata-core-1.7.1.jar:1.7.1]
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [classes!/:1.7.1]
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-1.7.1.jar:1.7.1]
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:523) [classes!/:1.7.1]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.handleRequestsByMergedWarpMessage(ServerOnRequestProcessor.java:288) [seata-core-1.7.1.jar:1.7.1]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.lambda$onRequestMessage$1(ServerOnRequestProcessor.java:178) [seata-core-1.7.1.jar:1.7.1]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

**Comment by funky-eyes** [comment]
这个不是其他节点提交，你的分支事务还在注册中，你用了异步线程去跑分支事务，主线程已经将事务决议了
This is not committed by other nodes. Your branch transaction is still registered. You used an asynchronous thread to run the branch transaction. The main thread has already decided the transaction.

**Comment by xuwei919** [comment]
在单节点时，我这个业务能够正常执行，分布式事务也是ok的，只有多节点才会报这个错，而且不是必现的
