### ISSUE TITLE
Unreal local address obtained by io.seata.common.util.NetUtil#getLocalIp

### ISSUE THREAD

**Issue by bydongxing** [apache/incubator-seata#6251]
### Ⅰ. Issue Description

When the project started, the 192.168.64.1 obtained is not my real ip.

### Ⅱ. Describe what happened

```
2024-01-10 12:11:41.145  INFO [26943, ] --- [main] i.s.core.rpc.netty.NettyPoolableFactory  : NettyPool create channel to transactionRole:TMROLE,address:193.168.11.122:8092,msg:< RegisterTMRequest{version='2.0.0', applicationId='stock-service', transactionServiceGroup='default-tx-group', extraData='ak=null
digest=default-tx-group,192.168.64.1,1704859901143
timestamp=1704859901143
authVersion=V4
vgroup=default-tx-group
ip=192.168.64.1
'} >
2024-01-10 12:11:41.152 ERROR [26943, ] --- [NettyClientSelector_TMROLE_1_1] i.s.c.r.n.AbstractNettyRemotingClient    : 0318

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_381]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_381]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_381]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_381]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378) ~[na:1.8.0_381]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.84.Final.jar:4.1.84.Final]
```

### Ⅲ. Describe what you expected to happen

My local real ip is 193.168.11.122.

<img width="584" alt="image" src="https://github.com/apache/incubator-seata/assets/32316182/60f97a74-1148-4945-a6d5-d1ff96f1fcf2">

![image](https://github.com/apache/incubator-seata/assets/32316182/38bb4f68-15ff-49f9-bf09-8aee6aeb2804)

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):  1.8
- Seata client/server version:  2.0.0
- Database version: mysql8
- OS(e.g. `uname -a`): macOS
- Others:

**Comment by liuqiufeng** [comment]
是否存在多个网卡？如果存在多个网卡，请确保server的SEATA_IP配置无误或设置一下网卡偏好。
Is there more than one network card? If there are multiple NICs, make sure the server's SEATA_IP is configured correctly. Or set the network card preferences.

**Comment by bydongxing** [comment]
> 是否存在多个网卡？如果存在多个网卡，请确保server的SEATA_IP配置无误或设置一下网卡偏好。 Is there more than one network card? If there are multiple NICs, make sure the server's SEATA_IP is configured correctly. Or set the network card preferences.

是有多个网卡的，server 的SEATA_IP 配置是正确的，`address:193.168.11.122:8092` ,这个就是我本地 server 的地址， 如何设置网卡偏好？我直接使用 hutool 的工具包获取到的是我本地真实的 ip

**Comment by funky-eyes** [comment]
See the `preferred-networks` configuration item in this configuration file https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.example.yml

**Comment by slievrly** [comment]
@bydongxing Referring to the above method, has your issue been resolved?

**Comment by bydongxing** [comment]
我试了下还是不行，我看这边调用获取 本地 IP 的时候，并没有把 `preferred-networks` 配置的选项传递进来，不知道是不是我使用的问题？
![image](https://github.com/apache/incubator-seata/assets/32316182/ace9438f-b45a-40f8-8bc0-37722d102c1e)

![image](https://github.com/apache/incubator-seata/assets/32316182/ef41accf-f475-4e67-a536-2e31556b6a73)

![image](https://github.com/apache/incubator-seata/assets/32316182/c6dc4274-b941-4c81-8cc0-722875a4132b)

**Comment by leizhiyuan** [comment]
please debug this line
```
String preferredNetworks = ConfigurationFactory.getInstance().getConfig(REGISTRY_PREFERED_NETWORKS);
            if (StringUtils.isNotBlank(preferredNetworks)) {
                XID.setIpAddress(NetUtil.getLocalIp(preferredNetworks.split(REGEX_SPLIT_CHAR)));
            } else {
                XID.setIpAddress(NetUtil.getLocalIp());
            }
```

it seems need to

    String REGISTRY_PREFERED_NETWORKS = ConfigurationKeys.FILE_ROOT_REGISTRY + ".preferredNetworks";


not preferred-networks

**Comment by bydongxing** [comment]
> please debug this line
> 
> ```
> String preferredNetworks = ConfigurationFactory.getInstance().getConfig(REGISTRY_PREFERED_NETWORKS);
>             if (StringUtils.isNotBlank(preferredNetworks)) {
>                 XID.setIpAddress(NetUtil.getLocalIp(preferredNetworks.split(REGEX_SPLIT_CHAR)));
>             } else {
>                 XID.setIpAddress(NetUtil.getLocalIp());
>             }
> ```
> 
> it seems need to
> 
> ```
> String REGISTRY_PREFERED_NETWORKS = ConfigurationKeys.FILE_ROOT_REGISTRY + ".preferredNetworks";
> ```
> 
> not preferred-networks

我在这边打断点，好像并没有调用这个方法呢？
![CleanShot 2024-01-25 at 09 02 58](https://github.com/apache/incubator-seata/assets/32316182/5f0b2375-2735-4222-a90b-1a5d6db01c83)

**Comment by leizhiyuan** [comment]
那看代码，没有别的地方会获取这个配置来传递到netutil方法的。

这个你看看走到你之前debug 为空入参的时候，这个调用栈是怎么样的

**Comment by funky-eyes** [comment]
> 我试了下还是不行，我看这边调用获取 本地 IP 的时候，并没有把 `preferred-networks` 配置的选项传递进来，不知道是不是我使用的问题？ ![image](https://private-user-images.githubusercontent.com/32316182/297269134-ace9438f-b45a-40f8-8bc0-37722d102c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDY4NjAsIm5iZiI6MTcwNjE0NjU2MCwicGF0aCI6Ii8zMjMxNjE4Mi8yOTcyNjkxMzQtYWNlOTQzOGYtYjQ1YS00MGY4LThiYzAtMzc3MjJkMTAyYzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzBjZWU2NDMyZWMwNzQ2MjRjY2E5YTcwZGIxOTg3NGY1ZWVmYjY1OGNhZmRkZTAyYzE4OWM2YmFhMTdlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS9STuWIykFOAIauKELq27riqe2VgN-HWi3QVsCHGGY)
> 
> ![image](https://private-user-images.githubusercontent.com/32316182/297269249-ef41accf-f475-4e67-a536-2e31556b6a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDY4NjAsIm5iZiI6MTcwNjE0NjU2MCwicGF0aCI6Ii8zMjMxNjE4Mi8yOTcyNjkyNDktZWY0MWFjY2YtZjQ3NS00ZTY3LWE1MzYtMmUzMTU1NmI2YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjJkMzQwOWMwZWYxODIwMjE4NzE1NDE0ZTk2ZmM4ZmJjMDg2M2Y2YWQ2N2MzOGFlY2Y3Yjg0Y2QyZDUzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kWD17C6ZoIZ7XKRzWd7Pl5R-gO1GLw1xfm5pxCHMWHc)
> 
> ![image](https://private-user-images.githubusercontent.com/32316182/297269366-c6dc4274-b941-4c81-8cc0-722875a4132b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDY4NjAsIm5iZiI6MTcwNjE0NjU2MCwicGF0aCI6Ii8zMjMxNjE4Mi8yOTcyNjkzNjYtYzZkYzQyNzQtYjk0MS00YzgxLThjYzAtNzIyODc1YTQxMzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWUxYTE1ZTZmNTE2ZThhOTc1NmM3NzRhMWRlZjFlZjM5Y2QyZTJlM2FlZGU3YmI5NWFmZDA2Y2IzZDc3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eexybt-zd470S_2YMnn35VavYwVET2YR3N2MID-jtck)

Is the ip you're talking about the CLIENT side or the SERVER side?
你说的ip到底是client侧还是server侧

**Comment by bydongxing** [comment]
> > 我试了下还是不行，我看这边调用获取 本地 IP 的时候，并没有把 `preferred-networks` 配置的选项传递进来，不知道是不是我使用的问题？ ![image](https://private-user-images.githubusercontent.com/32316182/297269134-ace9438f-b45a-40f8-8bc0-37722d102c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDY4NjAsIm5iZiI6MTcwNjE0NjU2MCwicGF0aCI6Ii8zMjMxNjE4Mi8yOTcyNjkxMzQtYWNlOTQzOGYtYjQ1YS00MGY4LThiYzAtMzc3MjJkMTAyYzFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNzBjZWU2NDMyZWMwNzQ2MjRjY2E5YTcwZGIxOTg3NGY1ZWVmYjY1OGNhZmRkZTAyYzE4OWM2YmFhMTdlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS9STuWIykFOAIauKELq27riqe2VgN-HWi3QVsCHGGY)
> > ![image](https://private-user-images.githubusercontent.com/32316182/297269249-ef41accf-f475-4e67-a536-2e31556b6a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDY4NjAsIm5iZiI6MTcwNjE0NjU2MCwicGF0aCI6Ii8zMjMxNjE4Mi8yOTcyNjkyNDktZWY0MWFjY2YtZjQ3NS00ZTY3LWE1MzYtMmUzMTU1NmI2YTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjJkMzQwOWMwZWYxODIwMjE4NzE1NDE0ZTk2ZmM4ZmJjMDg2M2Y2YWQ2N2MzOGFlY2Y3Yjg0Y2QyZDUzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kWD17C6ZoIZ7XKRzWd7Pl5R-gO1GLw1xfm5pxCHMWHc)
> > ![image](https://private-user-images.githubusercontent.com/32316182/297269366-c6dc4274-b941-4c81-8cc0-722875a4132b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDY4NjAsIm5iZiI6MTcwNjE0NjU2MCwicGF0aCI6Ii8zMjMxNjE4Mi8yOTcyNjkzNjYtYzZkYzQyNzQtYjk0MS00YzgxLThjYzAtNzIyODc1YTQxMzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxMzYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWUxYTE1ZTZmNTE2ZThhOTc1NmM3NzRhMWRlZjFlZjM5Y2QyZTJlM2FlZGU3YmI5NWFmZDA2Y2IzZDc3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Eexybt-zd470S_2YMnn35VavYwVET2YR3N2MID-jtck)
> 
> Is the ip you're talking about the CLIENT side or the SERVER side? 你说的ip到底是client侧还是server侧

client 侧的，就是我本地是多网卡的，然后启动 seata 的 client 的时候，获取到的 IP 有问题的

**Comment by funky-eyes** [comment]
client侧并没有这个配置，怪不得没有生效，请问这个ip不对的情况下，对server二阶段的下发产生了影响吗？
The client side doesn't have this configuration, so no wonder it didn't take effect, did this ip not being correct have an effect on the server second stage down?
