### ISSUE TITLE
seata2.0 Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-seata#6258]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Request to save batch data with exception thrown

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
2024-01-12T18:57:34.955+08:00 ERROR 33192 --- [samplesAccount] [ctor_RMROLE_1_1] i.s.c.rpc.netty.AbstractNettyRemoting    : 0104

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at io.seata.core.rpc.processor.client.ClientOnResponseProcessor.process(ClientOnResponseProcessor.java:103) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.core.rpc.netty.AbstractNettyRemoting.processMessage(AbstractNettyRemoting.java:306) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient$ClientHandler.channelRead(AbstractNettyRemotingClient.java:411) ~[seata-all-2.0.0.jar:2.0.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.104.Final.jar:4.1.104.Final]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
```

### Ⅲ. Describe what you expected to happen
Request to save data successful

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
This issue is similar to bug [# 5282] parallel request handle throw IndexOutOfBoundsException

Minimal yet complete reproducer code (or URL to code):
https://github.com/seata/seata/pull/5282

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 17
- Seata client/server version:  2.0.0
- Database version: MySQL 8.0.33
- OS(e.g. `uname -a`): Linux
- Others: mybatis-plus 3.5.5

**Comment by funky-eyes** [comment]
Are there any exceptions in the logs on the seata-server side at this time?

**Comment by funky-eyes** [comment]
And make sure your server is 2.0.

**Comment by laywin** [comment]
it seems no response messsge in a mergedWarpMessage, but exist  in request. i test normal case in 2.0.0 is ok. it need detail info, server side log or sample case.

**Comment by Python-IBM** [comment]
> it seems no response messsge in a mergedWarpMessage, but exist in request. i test normal case in 2.0.0 is ok. it need detail info, server side log or sample case.

After restarting the computer, attempting to submit and save batch data again did not encounter similar issues.

**Comment by Python-IBM** [comment]
> And make sure your server is 2.0.

![image](https://github.com/apache/incubator-seata/assets/33851767/45f1f22e-b07a-4788-b889-5c799b412a20)
The exception message shows that the seata server version is 2.0

**Comment by Python-IBM** [comment]
> And make sure your server is 2.0.

![image](https://github.com/apache/incubator-seata/assets/33851767/45f1f22e-b07a-4788-b889-5c799b412a20)
The exception message shows that the seata server version is 2.0

**Comment by funky-eyes** [comment]
> > And make sure your server is 2.0.
> 
> ![image](https://private-user-images.githubusercontent.com/33851767/296400658-45f1f22e-b07a-4788-b889-5c799b412a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTQxNTAsIm5iZiI6MTcwNTExMzg1MCwicGF0aCI6Ii8zMzg1MTc2Ny8yOTY0MDA2NTgtNDVmMWYyMmUtYjA3YS00Nzg4LWI4ODktNWM3OTliNDEyYTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDAyNDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MWViZTAzNjg2YTc4YTdmZTllMzQwNmYzODkwOGU0ODE2Yzc0ODZjZDAwNWI1NjhiYTdhODc1MzNhN2M5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fEKAcnSf2FG3VHfDDvF-6iN_42f-J0BI9xlw9jN5-u8) The exception message shows that the seata server version is 2.0

This is just your client version
