### ISSUE TITLE
TCC模式开启useTCCFence = true报空指针异常

### ISSUE THREAD

**Issue by htwdjqr** [apache/incubator-seata#6266]
### Ⅰ. Issue Description
TCC模式开启useTCCFence = true 报空指针异常

### Ⅱ. Describe what happened
异常堆栈信息：
```
java.lang.NullPointerException: null
	at io.seata.rm.tcc.TCCFenceHandler.prepareFence(TCCFenceHandler.java:109) ~[seata-all-1.7.0.jar:1.7.0]
	at io.seata.rm.tcc.interceptor.ActionInterceptorHandler.proceed(ActionInterceptorHandler.java:94) ~[seata-all-1.7.0.jar:1.7.0]
	at io.seata.spring.tcc.TccActionInterceptor.invoke(TccActionInterceptor.java:100) ~[seata-all-1.7.0.jar:1.7.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.15.jar:5.3.15]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.15.jar:5.3.15]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.15.jar:5.3.15]
	at com.yimo.simple.stock.tcc.StockTccActionImpl$$EnhancerBySpringCGLIB$$24127c4d.prepare(<generated>) ~[na:na]
	at com.yimo.simple.stock.dubbo.StockDubboServiceImpl.tccDecreaseStock(StockDubboServiceImpl.java:51) ~[na:na]
	at org.apache.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.15.jar:2.7.15]
	at com.alibaba.dubbo.rpc.Invoker$CompatibleInvoker.invoke(Invoker.java:55) ~[dubbo-2.7.15.jar:2.7.15]
	at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:45) ~[seata-all-1.7.0.jar:1.7.0]
	at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:46) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.seata.SeataTransactionPropagationProviderFilter.invoke(SeataTransactionPropagationProviderFilter.java:66) ~[dubbo-filter-seata-1.0.2.jar:1.0.2]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:91) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:52) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:192) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:129) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.FilterNode.invoke(FilterNode.java:61) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:148) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-2.7.15.jar:2.7.15]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[dubbo-2.7.15.jar:2.7.15]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41) ~[dubbo-2.7.15.jar:2.7.15]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
```
### Ⅵ. Environment:
- Seata client/server version:  1.7.0
- Dubbo version: 2.7.15
- Spring Boot version: 2.6.3
- Spring Cloud Alibaba: 2021.0.1.0

**Comment by funky-eyes** [comment]
请检查SeataTCCFenceAutoConfiguration中SpringFenceConfig是否被加载
Please check if SpringFenceConfig is loaded in SeataTCCFenceAutoConfiguration!

**Comment by htwdjqr** [comment]
> 请检查SeataTCCFenceAutoConfiguration中SpringFenceConfig是否被加载 Please check if SpringFenceConfig is loaded in SeataTCCFenceAutoConfiguration!

引入的依赖是seata-all，没有SeataTCCFenceAutoConfiguration类

**Comment by funky-eyes** [comment]
如果是使用seata-all 需要自行创建SpringFenceConfig bean
If you are using seata-all, you need to create your own SpringFenceConfig bean.

**Comment by htwdjqr** [comment]
问题已解决，通过引入spring-cloud-starter-alibaba-seata依赖，而不是之前的seata-all
```
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
        </dependency>
```
