### ISSUE TITLE
seata-server报错，版本是2.0.0。

### ISSUE THREAD

**Issue by hobartaoxiang** [apache/incubator-seata#6389]
![save](https://github.com/apache/incubator-seata/assets/162080501/7b4bf127-6bc8-4b86-8b27-e612a124256b)
**调用save来insert到数据库，**

**idea里是显示这个错：**
![index](https://github.com/apache/incubator-seata/assets/162080501/ef44c727-94b9-4fbd-a046-00250c61c2e0)

**seata-server就报这个错：**
![serveer0](https://github.com/apache/incubator-seata/assets/162080501/38be9102-6748-4886-9021-eb4c6fec4342)

Key='public.t_user_type:54', applicationData='{"skipCheckLock":true}'}, clientIp: 192.168.3.27, vgroup: freebeauty_tx_group
java.util.ServiceConfigurationError: com.alipay.sofa.jraft.rpc.RaftRpcFactory: could not find any implementation for class
        at com.alipay.sofa.jraft.util.JRaftServiceLoader.fail(JRaftServiceLoader.java:161)
        at com.alipay.sofa.jraft.util.JRaftServiceLoader.first(JRaftServiceLoader.java:113)
        at com.alipay.sofa.jraft.util.RpcFactoryHelper.<clinit>(RpcFactoryHelper.java:28)
        at com.alipay.sofa.jraft.rpc.ProtobufMsgFactory.<clinit>(ProtobufMsgFactory.java:57)
        at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.<clinit>(AbstractClientService.java:63)
        at com.alipay.sofa.jraft.core.CliServiceImpl.init(CliServiceImpl.java:88)
        at com.alipay.sofa.jraft.core.CliServiceImpl.init(CliServiceImpl.java:73)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitCliService(RaftServiceFactory.java:65)
        at io.seata.server.cluster.raft.RaftServerFactory$SingletonHandler.<clinit>(RaftServerFactory.java:233)
        at io.seata.server.cluster.raft.RaftServerFactory.getInstance(RaftServerFactory.java:78)
        at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:316)
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:84)
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:153)
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:332)
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:77)
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:107)
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:299)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131)
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:523)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.handleRequestsByMergedWarpMessage(ServerOnRequestProcessor.java:288)
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.lambda$onRequestMessage$1(ServerOnRequestProcessor.java:178)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
11:33:41.310 ERROR --- [verHandlerThread_1_16_500] [erver.ServerOnRequestProcessor] [    onRequestMessage]  [] : handle request error: java.lang.ExceptionInInitializerError
==>
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[na:na]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:188) ~[seata-core-2.0.0.jar:2.0.0]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:122) ~[seata-core-2.0.0.jar:2.0.0]
        at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:280) ~[seata-core-2.0.0.jar:2.0.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.100.Final.jar:4.1.100.Final]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
Caused by: java.lang.ExceptionInInitializerError: null
        at com.alipay.sofa.jraft.core.CliServiceImpl.init(CliServiceImpl.java:88) ~[jraft-core-1.3.13.jar:na]
        at com.alipay.sofa.jraft.core.CliServiceImpl.init(CliServiceImpl.java:73) ~[jraft-core-1.3.13.jar:na]
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitCliService(RaftServiceFactory.java:65) ~[jraft-core-1.3.13.jar:na]
        at io.seata.server.cluster.raft.RaftServerFactory$SingletonHandler.<clinit>(RaftServerFactory.java:233) ~[classes!/:2.0.0]
        at io.seata.server.cluster.raft.RaftServerFactory.getInstance(RaftServerFactory.java:78) ~[classes!/:2.0.0]
        at io.seata.server.session.GlobalSession.addBranch(GlobalSession.java:316) ~[classes!/:2.0.0]
        at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:84) ~[classes!/:2.0.0]
        at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:153) ~[classes!/:2.0.0]
        at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:332) ~[classes!/:2.0.0]
        at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:77) ~[classes!/:2.0.0]
        at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:107) ~[classes!/:2.0.0]
        at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:299) ~[classes!/:2.0.0]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[classes!/:2.0.0]
        at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[classes!/:2.0.0]
        at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131) ~[seata-core-2.0.0.jar:2.0.0]
        at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) ~[classes!/:2.0.0]
        at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) ~[seata-core-2.0.0.jar:2.0.0]
        at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:523) ~[classes!/:2.0.0]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.handleRequestsByMergedWarpMessage(ServerOnRequestProcessor.java:288) ~[seata-core-2.0.0.jar:2.0.0]
        at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.lambda$onRequestMessage$1(ServerOnRequestProcessor.java:178) ~[seata-core-2.0.0.jar:2.0.0]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
Caused by: java.lang.IllegalStateException: Parse protocol file failed.
        at com.alipay.sofa.jraft.rpc.ProtobufMsgFactory.load(ProtobufMsgFactory.java:88) ~[jraft-core-1.3.13.jar:na]
        at com.alipay.sofa.jraft.rpc.impl.AbstractClientService.<clinit>(AbstractClientService.java:63) ~[jraft-core-1.3.13.jar:na]
        ... 27 common frames omitted
<==

11:33:56.253  INFO --- [     batchLoggerPrint_1_1] [ocessor.server.BatchLogHandler] [                 run]  [] : receive msg[single]: GlobalRollbackRequest{xid='192.168.3.27:8091:6296528255410147373', extraData='null'}, clientIp: 192.168.3.27, vgroup: freebeauty_tx_group
11:33:56.337  INFO --- [     batchLoggerPrint_1_1] [ocessor.server.BatchLogHandler] [                 run]  [] : receive msg[single]: BranchRollbackResponse{xid='192.168.3.27:8091:6296528255410147373', branchId=6296528255410147375, branchStatus=PhaseTwo_Rollbacked, resultCode=Success, msg='null'}, clientIp: 192.168.3.27, vgroup: freebeauty_tx_group

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/pull/6089

**Comment by iLiXiaoFeng** [comment]
how fix it

**Comment by 18620936193** [comment]
修复了嘛，我找了好半天没找到具体原因

**Comment by HUOYA33** [comment]
哥们哥们, 解决问题了吗? 我也遇到这个了
