### ISSUE TITLE
单机模式、nacos1.2.0、seata1.4.0偶发性异常

### ISSUE THREAD

**Issue by eb-zsl** [apache/incubator-seata#6392]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
微服务偶尔报错找不到seata server，总体频率大概在百分之一，此外，出现此问题操作的表集中在同一张

### Ⅱ. Describe what happened

io.seata.common.exception.FrameworkException: No available service
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.loadBalance(AbstractNettyRemotingClient.java:261)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.sendSyncRequest(AbstractNettyRemotingClient.java:141)
        at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95)
        at io.seata.tm.DefaultTransactionManager.begin(DefaultTransactionManager.java:53)
        at io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:105)
        at io.seata.tm.api.TransactionalTemplate.beginTransaction(TransactionalTemplate.java:215)
        at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:122)
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:181)
        at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:150)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at com.ebupt.cmi.clientmanagement.consumer.hvshare.strategy.singledaydelay.SingleDayDelayStrategy$$EnhancerBySpringCGLIB$$855265dc.handle(<generated>)
        at com.ebupt.cmi.clientmanagement.consumer.hvshare.SingleDayResumeConsumer.process(SingleDayResumeConsumer.java:64)
        at sun.reflect.GeneratedMethodAccessor1300.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:170)
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
        at org.springframework.amqp.rabbit.listener.adapter.DelegatingInvocableHandler.invoke(DelegatingInvocableHandler.java:130)
        at org.springframework.amqp.rabbit.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:60)
        at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:190)
        at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:127)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1547)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1473)
        at sun.reflect.GeneratedMethodAccessor1186.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at brave.spring.rabbit.TracingRabbitListenerAdvice.invoke(TracingRabbitListenerAdvice.java:87)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at org.springframework.amqp.rabbit.listener.$Proxy382.invokeListener(Unknown Source)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1461)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1456)
        at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1405)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:870)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:854)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:78)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1137)
        at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1043)
        at java.lang.Thread.run(Thread.java:745)

### Ⅲ. Describe what you expected to happen
请问各位大佬我该怎么解决这个问题

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 8.0
- Seata client/server version:  1.4.0
- Database version: Mysql 8 .0
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
Check the health of the seata service in nacos by yourself, and telnet the port to see if the network is normal when the exception occurs.

**Comment by eb-zsl** [comment]
> Check the health of the seata service in nacos by yourself, and telnet the port to see if the network is normal when the exception occurs.

我们发现此情况时，就检查了nacos上seata server 是否健康，答案是至少我们观察的期间它一直是健康的注册进nacos的。问题奇怪的点在于这种情况是特例，生产环境每秒都有业务再跑，但是大多数业务都能正常使用seata，偶然情况下就会发生在队列消费里面，我们是K8S搭建的环境，我是不是该重点关注K8S内部网络情况。

**Comment by funky-eyes** [comment]
> > Check the health of the seata service in nacos by yourself, and telnet the port to see if the network is normal when the exception occurs.
> 
> 我们发现此情况时，就检查了nacos上seata server 是否健康，答案是至少我们观察的期间它一直是健康的注册进nacos的。问题奇怪的点在于这种情况是特例，生产环境每秒都有业务再跑，但是大多数业务都能正常使用seata，偶然情况下就会发生在队列消费里面，我们是K8S搭建的环境，我是不是该重点关注K8S内部网络情况。

Yes, I suggest you start a process to do network monitoring of the seata server in pod, and there should be other exception logs right before outputting this one, it won't just be this one
是的，我建议你启动一个进程，在pod中做对seata server的网络监控，而且输出这个日志之前应该就会有其他的异常日志，不会只有这么一些

**Comment by eb-zsl** [comment]
> > > Check the health of the seata service in nacos by yourself, and telnet the port to see if the network is normal when the exception occurs.
> > 
> > 
> > 我们发现此情况时，就检查了nacos上seata server 是否健康，答案是至少我们观察的期间它一直是健康的注册进nacos的。问题奇怪的点在于这种情况是特例，生产环境每秒都有业务再跑，但是大多数业务都能正常使用seata，偶然情况下就会发生在队列消费里面，我们是K8S搭建的环境，我是不是该重点关注K8S内部网络情况。
> 
> Yes, I suggest you start a process to do network monitoring of the seata server in pod, and there should be other exception logs right before outputting this one, it won't just be this one 是的，我建议你启动一个进程，在pod中做对seata server的网络监控，而且输出这个日志之前应该就会有其他的异常日志，不会只有这么一些

您好，我们似乎有些发现，我想知道seata是否也会像各微服务一样，每5S向nacos报告自己的状态是否正常喃？

**Comment by funky-eyes** [comment]
> > > > Check the health of the seata service in nacos by yourself, and telnet the port to see if the network is normal when the exception occurs.
> > > 
> > > 
> > > 我们发现此情况时，就检查了nacos上seata server 是否健康，答案是至少我们观察的期间它一直是健康的注册进nacos的。问题奇怪的点在于这种情况是特例，生产环境每秒都有业务再跑，但是大多数业务都能正常使用seata，偶然情况下就会发生在队列消费里面，我们是K8S搭建的环境，我是不是该重点关注K8S内部网络情况。
> > 
> > 
> > Yes, I suggest you start a process to do network monitoring of the seata server in pod, and there should be other exception logs right before outputting this one, it won't just be this one 是的，我建议你启动一个进程，在pod中做对seata server的网络监控，而且输出这个日志之前应该就会有其他的异常日志，不会只有这么一些
> 
> 您好，我们似乎有些发现，我想知道seata是否也会像各微服务一样，每5S向nacos报告自己的状态是否正常喃？

seata uses nacos' standard client sdk, and specific health checks are handled by logic encapsulated inside the sdk
https://github.com/apache/incubator-seata/blob/v1.4.0/discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java

**Comment by funky-eyes** [comment]
Second, seata pulls the latest address from the registry every 10s and connects to it, retrying to connect after 10s if the current connection has been disconnected.

**Comment by eb-zsl** [comment]
> seata uses nacos' standard client sdk, and specific health checks are handled by logic encapsulated inside the sdk

thx，我们大致定位到原因了，我们通过连接seata与nacos 的 nginx的错误日志发现，seata向nacos报告自己状态时，偶尔可能由于网络波动（具体原因未知），nacos并没有收到此条消息，15s内3次都没收到，nacos把seata设为不健康实例，这段时间内可能就会有问题，再次感谢您的解答，祝您工作开心，生活愉快

**Comment by funky-eyes** [comment]
Solved it just fine, warm tips 1.4.0 and 1.4.1 these two versions in at mode on the dirty write risk, it is recommended to upgrade to 1.4.2 or above version.
