### ISSUE TITLE
springmvc + dubbo2.6.12+seata 1.8.0 程序启动提升这个错

### ISSUE THREAD

**Issue by junliudr** [apache/incubator-seata#6395]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.easyhome.cloudservice.timer.utils.TaskThread.run(TaskThread.java:37)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.alibaba.dubbo.rpc.RpcContext.getServerContext()Lcom/alibaba/dubbo/rpc/RpcContext;
	at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:98)
	at com.taobao.hsf2dubbo.DubboFilterUtil$1.invoke(DubboFilterUtil.java:67)
	at com.taobao.hsf2dubbo.DubboClientFilterSyncInvocationHandlerInterceptor.invoke(DubboClientFilterSyncInvocationHandlerInterceptor.java:64)
	at com.taobao.hsf.rpc.client.ClientConcurrencyLimiter.invoke(ClientConcurrencyLimiter.java:41)
	at com.taobao.hsf.InvocationUtil.invoke(InvocationUtil.java:51)
	at com.taobao.hsf.proxy.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:31)
	at com.taobao.hsf.proxy.bytecode.proxy44.runJob(proxy44.java)
	... 6 more

**Comment by funky-eyes** [comment]
com.alibaba.dubbo.rpc.RpcContext.getServerContext()Lcom/alibaba/dubbo/rpc/RpcContext; 
Please check if this method exists

**Comment by junliudr** [comment]
dubbo 2.6.12 + seata 1.5.2 有这个方法

**Comment by junliudr** [comment]
dubbo 2.6.12 + seata 1.8.0 有这个方法

**Comment by junliudr** [comment]
<html>
<body>

Caused by: java.lang.NoSuchMethodError: com.alibaba.dubbo.rpc.RpcContext.getServerContext()Lcom/alibaba/dubbo/rpc/RpcContext;
--
  | at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:98) ~[seata-all-1.8.0.jar:1.8.0]
  | at com.taobao.hsf2dubbo.DubboFilterUtil$1.invoke(DubboFilterUtil.java:67) ~[hsf-service-dubbo-2.2.8.7-EDAS-1.jar!/:na]


</body>
</html>

**Comment by junliudr** [comment]
![image](https://github.com/apache/incubator-seata/assets/162402337/e5d1fcb3-78ef-4aab-85bf-900102438ded)

**Comment by xingfudeshi** [comment]
You need to add this dependency to pom.xml

```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.12</version>
        </dependency>
```

**Comment by junliudr** [comment]
用得就是这个版本

**Comment by slievrly** [comment]
add configuration on serviceBean and referenceBean config `filter=-alibabadubbotransactionpropagation`
