### ISSUE TITLE
 io.seata.common.exception.FrameworkException: method not found

### ISSUE THREAD

**Issue by junliudr** [apache/incubator-seata#6399]
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name '': Initialization of bean failed; nested exception is java.lang.RuntimeException: io.seata.common.exception.FrameworkException: method not found: Method<ServiceBean.getInterfaceClass()>
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5182) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5705) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:819) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2119) [catalina.jar:7.0.92.2568]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
Caused by: java.lang.RuntimeException: io.seata.common.exception.FrameworkException: method not found: Method<ServiceBean.getInterfaceClass()>
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:322) ~[seata-all-1.5.2.jar:1.5.2]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 24 common frames omitted
Caused by: io.seata.common.exception.FrameworkException: method not found: Method<ServiceBean.getInterfaceClass()>
	at io.seata.rm.tcc.remoting.parser.DubboRemotingParser.getServiceDesc(DubboRemotingParser.java:66) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.rm.tcc.remoting.parser.DefaultRemotingParser.parserRemotingServiceInfo(DefaultRemotingParser.java:167) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.spring.util.TCCBeanParserUtils.parserRemotingServiceInfo(TCCBeanParserUtils.java:179) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.spring.util.TCCBeanParserUtils.isTccAutoProxy(TCCBeanParserUtils.java:50) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:280) ~[seata-all-1.5.2.jar:1.5.2]
	... 28 common frames omitted
Caused by: java.lang.NoSuchMethodException: method not found: Method<ServiceBean.getInterfaceClass()>
	at io.seata.common.util.ReflectionUtil.getMethod(ReflectionUtil.java:406) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.common.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:505) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.common.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:524) ~[seata-all-1.5.2.jar:1.5.2]
	at io.seata.rm.tcc.remoting.parser.DubboRemotingParser.getServiceDesc(DubboRemotingParser.java:51) ~[seata-all-1.5.2.jar:1.5.2]
	... 32 common frames omitted
```

**Comment by funky-eyes** [comment]
Please provide examples of how this problem can be reproduced.

**Comment by junliudr** [comment]
我是直接使用的 dubbo2.8.4 + seata-all 1.5.2 + mybatis-plus 2.0.2 非start方式。 serverce不增加GlobalTransactional注解

**Comment by junliudr** [comment]
springmvc

**Comment by funky-eyes** [comment]
Please test with 2.0

**Comment by junliudr** [comment]
seata-all 2.0.0版本么

**Comment by xingfudeshi** [comment]
> seata-all 2.0.0版本么

Yes.Or provide an example that can be used to reproduce the problem.

**Comment by junliudr** [comment]
seata-all 2.0.0 和spring 4.3.7.RELEASE版本有类加载问题么
