### ISSUE TITLE
阿里巴巴dubbo2.6.12+ seata-all 1.8.0 报错

### ISSUE THREAD

**Issue by junliudr** [apache/incubator-seata#6407]
14:05:33.127 [localhost-startStop-1] ERROR [] o.s.web.context.ContextLoader Line:350 - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.easyhome.cloudservice.order.service.IIntegralMallReturnOrderService': Initialization of bean failed; nested exception is java.lang.RuntimeException: io.seata.common.exception.FrameworkException: method not found: Method<ServiceBean.getInterfaceClass()>
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5182) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5705) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:819) [catalina.jar:7.0.92.2568]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2119) [catalina.jar:7.0.92.2568]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
Caused by: java.lang.RuntimeException: io.seata.common.exception.FrameworkException: method not found: Method<ServiceBean.getInterfaceClass()>
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:325) ~[seata-all-1.8.0.jar:1.8.0]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 24 common frames omitted
Caused by: io.seata.common.exception.FrameworkException: method not found: Method<ServiceBean.getInterfaceClass()>
	at io.seata.rm.tcc.remoting.parser.DubboRemotingParser.getServiceDesc(DubboRemotingParser.java:66) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.rm.tcc.remoting.parser.DefaultRemotingParser.parserRemotingServiceInfo(DefaultRemotingParser.java:167) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.spring.util.TCCBeanParserUtils.parserRemotingServiceInfo(TCCBeanParserUtils.java:179) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.spring.util.TCCBeanParserUtils.isTccAutoProxy(TCCBeanParserUtils.java:50) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.wrapIfNecessary(GlobalTransactionScanner.java:283) ~[seata-all-1.8.0.jar:1.8.0]
	... 28 common frames omitted
Caused by: java.lang.NoSuchMethodException: method not found: Method<ServiceBean.getInterfaceClass()>
	at io.seata.common.util.ReflectionUtil.getMethod(ReflectionUtil.java:465) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.common.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:564) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.common.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:583) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.rm.tcc.remoting.parser.DubboRemotingParser.getServiceDesc(DubboRemotingParser.java:51) ~[seata-all-1.8.0.jar:1.8.0]
	... 32 common frames omitted

**Comment by funky-eyes** [comment]
Please provide code and examples that reproduce the problem

**Comment by junliudr** [comment]
![image](https://github.com/apache/incubator-seata/assets/162402337/e13b093d-778e-4cc3-9abf-51b464f2f676)

**Comment by junliudr** [comment]
![image](https://github.com/apache/incubator-seata/assets/162402337/0cf0eb1e-63c2-49ac-8ca1-9410c97114cf)

**Comment by slievrly** [comment]
At present, the question has been located. TCC parser parsing affects AT mode processing.
