### ISSUE TITLE
XA模式下，同一个本地事务中对同一张表进行多次更新，提示：Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by hongmin118** [apache/incubator-seata#6432]
### Ⅰ. Issue Description
XA模式下，同一个本地事务中对同一张表进行多次更新，提示：Lock wait timeout exceeded; try restarting transaction

### Ⅱ. Describe what happened
嵌套SQL在AT模式下不支持，所以想改到XA模式下，结果发现XA模式下有点问题。

业务流程：订单服务(生成订单)->商品服务(扣除商品个数)->账户服务(更新账户金额)
其中商品服务中，扣除商品个数后(update语句)，又做了delete操作，如果使用`delete from table where id in (2,3,4)`这种语法没问题，如果使用`DELETE FROM MHM_GOODS WHERE id IN (select a.id from (SELECT id FROM MHM_GOODS WHERE id IN(2,3,4))a)`，则提示Lock wait timeout exceeded; try restarting transaction

如果直接执行商品服务的扣除接口，则不会抛错，只有在开启SEATA的XA模式下，从订单服务执行到商品服务时，才会出现这种问题。

```
Caused by: org.springframework.dao.CannotAcquireLockException: 
### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
### The error may exist in file [C:\mhm\IdeaProjects\seata-master\_8_seata-at-cloud-master\_3-seata-at-cloud-goods\target\classes\mapper\goodsMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: DELETE FROM MHM_GOODS WHERE id IN         (         select a.id from (         SELECT id FROM MHM_GOODS WHERE id IN(2,3,4)         )a         )
### Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
; Lock wait timeout exceeded; try restarting transaction; nested exception is com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:267)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at com.sun.proxy.$Proxy102.delete(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:304)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:72)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:142)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:86)
	at com.sun.proxy.$Proxy103.deleteByIds(Unknown Source)
	at com.cz.mhm.service.impl.GoodsServiceImpl.reduceGoods(GoodsServiceImpl.java:106)
	at com.cz.mhm.service.impl.GoodsServiceImpl$$FastClassBySpringCGLIB$$f8777ece.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at io.seata.spring.annotation.AdapterInvocationWrapper.proceed(AdapterInvocationWrapper.java:57)
	... 57 more
```

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:   2.0.0
- Database version: mysql 8.0.24
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
把 扣除商品个数后(update语句)，又做了delete操作  这个动作合并到一个本地事务中，否则xa事务在prepare后是无法重入的
After deducting the number of goods (update statement), the delete operation is done. This action is merged into a local transaction, otherwise the xa transaction cannot be reentered after prepare

**Comment by hongmin118** [comment]
> 把 扣除商品个数后(update语句)，又做了delete操作 这个动作合并到一个本地事务中，否则xa事务在prepare后是无法重入的 After deducting the number of goods (update statement), the delete operation is done. This action is merged into a local transaction, otherwise the xa transaction cannot be reentered after prepare

Thanks for your support.
