### ISSUE TITLE
seata-all + springmvc 没有任何springboot的配置 多次数据库代理导致主键冲突

### ISSUE THREAD

**Issue by junliudr** [apache/incubator-seata#6433]
seata俩次数据库代理造成
39:36.601 ERROR --- [verHandlerThread_1_23_500] i.s.s.s.db.lock.LockStoreDataBaseDAO     : Global lock batch acqu
ire error: [17aab41f4cfa3000-5][172.16.89.95:3306][busi_pressure]ERR-CODE: [TDDL-4614][ERR_EXECUTE_ON_MYSQL] Error o
ccurs when execute on GROUP 'BUSI_PRESSURE_1582078948621MWMH_G6ST_0000' ATOM '': Duplicate entry 'jdbc:mysql://drdsb
ggaq2b6y9n5.drds.aliyuncs.com/member_pressure^' for key 'PRIMARY' 
==>
java.sql.BatchUpdateException: [17aab41f4cfa3000-5][172.16.89.95:3306][busi_pressure]ERR-CODE: [TDDL-4614][ERR_EXECU
TE_ON_MYSQL] Error occurs when execute on GROUP 'BUSI_PRESSURE_1582078948621MWMH_G6ST_0000' ATOM '': Duplicate entry
 'jdbc:mysql://drdsbggaq2b6y9n5.drds.aliyuncs.com/member_pressure^' for key 'PRIMARY' 
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1819)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1281)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:565)
	at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.doAcquireLocks(LockStoreDataBaseDAO.java:368)
	at io.seata.server.storage.db.lock.LockStoreDataBaseDAO.acquireLock(LockStoreDataBaseDAO.java:186)
	at io.seata.server.storage.db.lock.DataBaseLocker.acquireLock(DataBaseLocker.java:64)
	at io.seata.server.lock.AbstractLockManager.acquireLock(AbstractLockManager.java:65)
	at io.seata.server.session.BranchSession.lock(BranchSession.java:287)
	at io.seata.server.transaction.at.ATCore.branchSessionLock(ATCore.java:80)
	at io.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:83)
	at io.seata.server.storage.db.session.DataBaseSessionManager.lockAndExecute(DataBaseSessionManager.java:191)
	at io.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:365)
	at io.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:77)
	at io.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:102)
	at io.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:277)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184)
	at io.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131)
	at io.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179)
	at io.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136)
	at io.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:511)
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:175
)
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:117)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: [17aab41f4cfa3000-5][172.16.8
9.95:3306][busi_pressure]ERR-CODE: [TDDL-4614][ERR_EXECUTE_ON_MYSQL] Error occurs when execute on GROUP 'BUSI_PRESSU
RE_1582078948621MWMH_G6ST_0000' ATOM '': Duplicate entry 'jdbc:mysql://drdsbggaq2b6y9n5.drds.aliyuncs.com/member_pre
ssure^' for key 'PRIMARY' 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
	at com.mysql.jdbc.Util.getInstance(Util.java:372)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1777)
	... 27 common frames omitted
<==

**Comment by junliudr** [comment]
package com.easyhome.cloudservice.config;

import io.seata.spring.annotation.datasource.EnableAutoDataSourceProxy;
import org.springframework.beans.factory.annotation.Qualifier;
import com.alibaba.druid.pool.DruidDataSource;
import io.seata.rm.datasource.DataSourceProxy;
import io.seata.spring.annotation.GlobalTransactionScanner;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import javax.sql.DataSource;
import java.io.InputStream;
import java.util.Properties;

/**
 * Seata Config
 */
@Configuration
@Slf4j
@EnableAutoDataSourceProxy
public class SeataConfiguration {

//    @javax.annotation.Resource DruidDataSource dataSourceCommon;

    /**
     * 注册一个StatViewServlet
     *
     * @return global transaction scanner
     */
    @Bean
    public GlobalTransactionScanner globalTransactionScanner() {
        try {
            PathMatchingResourcePatternResolver patternResolver = new PathMatchingResourcePatternResolver();
            Resource[] resources = patternResolver.getResources("classpath*:/seata.properties");
            if ((resources != null) && (resources.length > 0)) {
                InputStream in = resources[0].getInputStream();
                Properties props = new Properties();
                props.load(in);
                String applicationId = props.getProperty("seata.applicationId", "");
                String txServiceGroup = props.getProperty("seata.tx-service-group", "");
                log.info("SeataConfiguration-applicationId:{}",applicationId);
                log.info("SeataConfiguration-txServiceGroup:{}",txServiceGroup);
                return new GlobalTransactionScanner(applicationId, txServiceGroup);
            }
        } catch (Exception e) {
            log.error("SeataConfiguration-globalTransactionScanner-error:{}", e.getMessage(),e);
        }
        return new GlobalTransactionScanner("", "");
    }

    @Bean(name = "druidDataSource") // 声明其为Bean实例
    public DataSource druidDataSource() {
        DruidDataSource druidDataSource = new DruidDataSource();
        druidDataSource.setUrl("jdbc:mysql://drdsbggaq2b6y9n5.drds.aliyuncs.com/member_pressure?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true");
        druidDataSource.setUsername("member_pressure_rw");
        druidDataSource.setPassword("pZ#*J8EfD!iIq54y");
        druidDataSource.setDriverClassName("com.mysql.jdbc.Driver");
        return druidDataSource;
    }

    @Bean(name = "dataSource")
    @Primary // 在同样的DataSource中，首先使用被标注的DataSource
    public DataSource dataSourcePoxy(@Qualifier(value = "druidDataSource") DruidDataSource druidDataSource) {
        return new DataSourceProxy(druidDataSource);
    }
}

**Comment by junliudr** [comment]
package com.easyhome.cloudservice.config;

import io.seata.spring.annotation.datasource.EnableAutoDataSourceProxy;
import org.springframework.beans.factory.annotation.Qualifier;
import com.alibaba.druid.pool.DruidDataSource;
import io.seata.rm.datasource.DataSourceProxy;
import io.seata.spring.annotation.GlobalTransactionScanner;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import javax.sql.DataSource;
import java.io.InputStream;
import java.util.Properties;

/**
 * Seata Config
 */
@Configuration
@Slf4j
@EnableAutoDataSourceProxy
public class SeataConfiguration {

//    @javax.annotation.Resource DruidDataSource dataSourceCommon;

    /**
     * 注册一个StatViewServlet
     *
     * @return global transaction scanner
     */
    @Bean
    public GlobalTransactionScanner globalTransactionScanner() {
        try {
            PathMatchingResourcePatternResolver patternResolver = new PathMatchingResourcePatternResolver();
            Resource[] resources = patternResolver.getResources("classpath*:/seata.properties");
            if ((resources != null) && (resources.length > 0)) {
                InputStream in = resources[0].getInputStream();
                Properties props = new Properties();
                props.load(in);
                String applicationId = props.getProperty("seata.applicationId", "");
                String txServiceGroup = props.getProperty("seata.tx-service-group", "");
                log.info("SeataConfiguration-applicationId:{}",applicationId);
                log.info("SeataConfiguration-txServiceGroup:{}",txServiceGroup);
                return new GlobalTransactionScanner(applicationId, txServiceGroup);
            }
        } catch (Exception e) {
            log.error("SeataConfiguration-globalTransactionScanner-error:{}", e.getMessage(),e);
        }
        return new GlobalTransactionScanner("", "");
    }

    @Bean(name = "druidDataSource") // 声明其为Bean实例
    public DataSource druidDataSource() {
        DruidDataSource druidDataSource = new DruidDataSource();
        druidDataSource.setUrl("");
        druidDataSource.setUsername("");
        druidDataSource.setPassword("");
        druidDataSource.setDriverClassName("");
        return druidDataSource;
    }

    @Bean(name = "dataSource")
    @Primary // 在同样的DataSource中，首先使用被标注的DataSource
    public DataSource dataSourcePoxy(@Qualifier(value = "druidDataSource") DruidDataSource druidDataSource) {
        return new DataSourceProxy(druidDataSource);
    }
}

**Comment by funky-eyes** [comment]
I don't see where you've proxied twice, and this log is only because you've manipulated multiple rows of data and performed bulk inserts, which means that your global lock has been occupied by other transactions, and this time it will hit an error log, but it won't affect the lock retry. After the lock retry will be first check and then insert, will not throw this exception, this is a normal phenomenon. Please check the server log to see which transaction holds the global lock.
没看到你哪里两次代理了，并且这个日志只是因为你操作了多行数据，执行了批量插入，说明你的全局锁已经被其他事务占用了，这个时候会打一个error日志，但是不影响锁重试。之后的锁重试会进行先查后插，就不会抛这个异常，这个是正常现象。请你通过server日志排查这个全局锁被哪个事务所持有

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/blob/v1.8.0/server/src/main/java/io/seata/server/storage/db/lock/LockStoreDataBaseDAO.java#L373
See the source code for yourself

**Comment by junliudr** [comment]
我这边的业务只对一个表做出了操作，没有其他任何的业务操作

**Comment by funky-eyes** [comment]
> 我这边的业务只对一个表做出了操作，没有其他任何的业务操作

把你server的日志全部提交上来，以及client侧如何去操作的数据
Submit all the logs from your server and how the client side goes about manipulating the data

**Comment by funky-eyes** [comment]
How can there be a unique index conflict if this data is not in tc's locktable?
tc的locktable中如果没有这个数据，怎么可能出现唯一索引冲突？

**Comment by junliudr** [comment]
![Uploading image.png…]()

**Comment by junliudr** [comment]
![image](https://github.com/apache/incubator-seata/assets/162402337/afa9b24c-e8e7-403d-ba2f-6a6a24f70352)

**Comment by funky-eyes** [comment]
You do have duplicate proxies, but your code hasn't created 2 datasourceproxies, you can remove @EnableAutoDataSourceProxy to turn off autoproxying. Then I suggest you to take a look at the server's lock table and see if there is any relevant lock record
你确实存在重复代理，但是你的代码并没有创建过2个datasourceproxy，你可以去掉@EnableAutoDataSourceProxy，使自动代理关闭。然后建议你去看一下server的lock table，有没有相关的lock记录

**Comment by junliudr** [comment]
这个我已经解决了 ，在springmvc得配置文件中增加了seata数据源代理
