### ISSUE TITLE
seata1.5.2 配置mysql集群连接方式的时候 使用错误

### ISSUE THREAD

**Issue by 1746695227** [apache/incubator-seata#6513]
问题描述如下：
Spring Cloud Alibaba 2.2.6.RELEASE + Spring Boot 2.3.2.RELEASE + seata 1.5.2 + mysql8.0

有若干个服务，服务A、服务B、服务C，并配置了seata 1.5.2,且正常使用，使用AT模式。

在使用MySql集群时候出现问题：
某个服务数据库配置如下：
服务A
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 1000
      max-evictable-idle-time-millis: 900000
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      time-between-eviction-runs-millis: 60000
    password: sa123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.41:19131,192.168.10.42:19131/assets?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root

问题出现在服务A、服务B、服务C使用mysql集群连接串时候，全局事务出现如下错误：

10:52:40.627 ERROR --- [Pool.commonPool-worker-11] io.seata.server.coordinator.DefaultCore  : Committing branch transaction exception: BR:4323970364623622157/4323970364623622146
No channel is available for resource[jdbc:mysql://192.168.10.41:19131,192.168.10.42:19131/assets]
==>
java.lang.RuntimeException: rm client is not connected. dbkey:jdbc:mysql://192.168.10.41:19131,192.168.10.42:19131/assets,clientId:assets:192.168.10.41:55934
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendSyncRequest(AbstractNettyRemotingServer.java:69)
	at io.seata.server.coordinator.AbstractCore.branchCommitSend(AbstractCore.java:175)
	at io.seata.server.coordinator.AbstractCore.branchCommit(AbstractCore.java:165)
	at io.seata.server.coordinator.DefaultCore.lambda$doGlobalCommit$1(DefaultCore.java:204)
	at io.seata.server.session.SessionHelper.forEach(SessionHelper.java:244)
	at io.seata.server.coordinator.DefaultCore.doGlobalCommit(DefaultCore.java:192)
	at io.seata.server.coordinator.DefaultCoordinator.lambda$handleAsyncCommitting$4(DefaultCoordinator.java:441)
	at io.seata.server.session.SessionHelper.lambda$forEach$0(SessionHelper.java:223)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
<==

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/issues/4344

**Comment by funky-eyes** [comment]
你的url应该是`jdbc:mysql:loadbalance://`开头的
Your URL should start with`jdbc:mysql:loadbalance://`

**Comment by 1746695227** [comment]
搞定了，谢谢！
