### ISSUE TITLE
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.

### ISSUE THREAD

**Issue by pkyit** [apache/incubator-seata#6617]
024-06-18 19:29:27.080  INFO 7368 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-192.168.106.235_8848-LOCAL-PRE-RELEASE] [add-listener] ok, tenant=LOCAL-PRE-RELEASE, dataId=transport.enableTmClientBatchSendRequest, group=SEATA_GROUP, cnt=2
2024-06-18 19:29:27.097  INFO 7368 --- [           main] i.s.core.rpc.netty.NettyClientBootstrap  : NettyClientBootstrap has started
2024-06-18 19:29:27.097  INFO 7368 --- [CAL-PRE-RELEASE] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[]
2024-06-18 19:29:27.098  INFO 7368 --- [           main] i.s.discovery.registry.RegistryFactory   : use registry center type: nacos
2024-06-18 19:29:27.112  INFO 7368 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-192.168.106.235_8848-LOCAL-PRE-RELEASE] [subscribe] service.vgroupMapping.szmzyl_tx_group+SEATA_GROUP+LOCAL-PRE-RELEASE
2024-06-18 19:29:27.113  INFO 7368 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-192.168.106.235_8848-LOCAL-PRE-RELEASE] [add-listener] ok, tenant=LOCAL-PRE-RELEASE, dataId=service.vgroupMapping.szmzyl_tx_group, group=SEATA_GROUP, cnt=1
2024-06-18 19:29:27.124 ERROR 7368 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : Failed to get available servers: service.vgroupMapping.szmzyl_tx_group configuration item is required

io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.szmzyl_tx_group configuration item is required
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:247) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:168) ~[seata-all-1.8.0.jar:1.8.0]
	at io.seata.core.rpc.netty.TmNettyRemotingClient.init(TmNettyRemotingClient.java:198) [seata-all-1.8.0.jar:1.8.0]
	at io.seata.tm.TMClient.init(TMClient.java:47) [seata-all-1.8.0.jar:1.8.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:223) [seata-all-1.8.0.jar:1.8.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:536) [seata-all-1.8.0.jar:1.8.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207) [spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:229) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at com.yinhai.Ta404Application.main(Ta404Application.java:36) ~[classes/:na]

**Comment by slievrly** [comment]
Pls check `service.vgroupMapping.szmzyl_tx_group configuration` if exist.

**Comment by DragonZru** [comment]
改为去nacos配置 service.vgroupMapping.base-tx-group=default ，springboot下，直接在application.properties 配置的话不生效（seata.service.vgroupMapping.base-tx-group=default）
