### ISSUE TITLE
2.0.0 访问7091 ，发现了sql错误

### ISSUE THREAD

**Issue by eocoo** [apache/incubator-seata#6644]
具体错误内容如下，可以确认下

```
17:38:02.910 ERROR --- [     http-nio-7091-exec-7] [lhost].[/].[dispatcherServlet]] [                 log]  [] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.seata.common.exception.StoreException: ERROR: column "lock_table.gmt_create" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 42] with root cause
==>
org.postgresql.util.PSQLException: ERROR: column "lock_table.gmt_create" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 42
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
```

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/blob/2.x/script/server/db/postgresql.sql
是用这个脚本创建的吗？
Was it created with this script?

**Comment by eocoo** [comment]
> https://github.com/apache/incubator-seata/blob/2.x/script/server/db/postgresql.sql 是用这个脚本创建的吗？ Was it created with this script?

对的

**Comment by funky-eyes** [comment]
你可以尝试修复这个问题吗？
Can you try to fix this problem?

**Comment by eocoo** [comment]
可以

**Comment by eocoo** [comment]
找到问题了（代码没问题），但是需要手动配置 store.db.dbType=postgresql，以为只要配置了jdbcUrl或driverClasss就可以的

![image](https://github.com/apache/incubator-seata/assets/12453756/a7474e8a-1090-4009-8252-1d36d04de5a4)
