### ISSUE TITLE
【seata-2.1.0】请问2.1.0版本在客户端启动的时候，出于什么考虑在启用AT模式下新增了undo_log 表是否存在的校验？

### ISSUE THREAD

**Issue by God-Gan** [apache/incubator-seata#6871]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
我记得2.0.0应该是没有这个校验的。目前项目是通过liquibase的changelog进行undo_log表的创建，当表还没创建完成时就提示undo_log表不存在了，请问除了手动创建表以外还有其它方式解决吗，比如通过配置什么参数？因为生产环境目前没法手动提前创建表。

### Ⅱ. Describe what happened

Caused by: java.lang.IllegalStateException: in AT mode, undo_log table not exist
    at org.apache.seata.rm.datasource.DataSourceProxy.checkUndoLogTableExist(DataSourceProxy.java:176)
    at org.apache.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:111)
    at org.apache.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:97)
    at org.apache.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:82)
    at org.apache.seata.spring.annotation.datasource.SeataAutoDataSourceProxyCreator.buildProxy(SeataAutoDataSourceProxyCreator.java:113)
    at org.apache.seata.spring.annotation.datasource.SeataAutoDataSourceProxyCreator.wrapIfNecessary(SeataAutoDataSourceProxyCreator.java:87)
    at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:318)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:434)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
    ... 110 common frames omitted

### Ⅲ. Describe what you expected to happen
希望可以添加参数判断是否需要校验undo_log表是否存在。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 17
- Seata client/server version:  2.1.0
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by funky-eyes** [comment]
如果用户生产环境忘记创建了undolog，进行了业务发布，出故障了谁负责？
If the user production environment forgets to create undolog and launches a business release, who is responsible for the failure?

**Comment by God-Gan** [comment]
默认检查我觉得是没有问题的，但是现在并没有额外的参数进行配置来校验，这就相当于通过liquibase这种场景来创建undo_log是没法使用的。

**Comment by funky-eyes** [comment]
生产环境一般不允许自动建表等操作

**Comment by God-Gan** [comment]
https://github.com/apache/incubator-seata/issues/6022 我看了是这个issue需要新增的校验，上面也提到了通过开关控制，不过最后应该还是没有通过开关控制，实现的时候应该是没有考虑到这种场景。我先看看能不能改bean的加载顺序吧，不行的话只能先临时手动创建了。(小小吐槽一句，之前那么多版本都没加这个限制，现在加了限制，感觉有点鸡肋，毕竟使用AT模式的话如果生产环境还不创建undo_log表，那心是真大hhh)。

**Comment by wanghongzhou** [comment]
@funky-eyes 添加这个校验无可厚非，看是否能找到更合适的校验时机。我项目使用的JPA，有UndoLog这个实体，开发环境依赖hibernate.hbm2ddl.auto=update自动维护表，测试和生产环境设置hibernate.hbm2ddl.auto=validate，用Flyway管理SQL脚本。如果没有undolog这个表，hibernate自然会报错了。现在这个检测会导致flyway管理的数据库初始化脚本都还没执行就启动报错了。

**Comment by funky-eyes** [comment]
> @funky-eyes 添加这个校验无可厚非，看是否能找到更合适的校验时机。我项目使用的JPA，有UndoLog这个实体，开发环境依赖hibernate.hbm2ddl.auto=update自动维护表，测试和生产环境设置hibernate.hbm2ddl.auto=validate，用Flyway管理SQL脚本。如果没有undolog这个表，hibernate自然会报错了。现在这个检测会导致flyway管理的数据库初始化脚本都还没执行就启动报错了。

不可能在运行中校验，运行中属于事中，要事前就校验处理，所以应该是启动立马校验。
It is impossible to verify during operation. It belongs to the process during operation, and it needs to be verified in advance, so it should be verified immediately after starting.

**Comment by wanghongzhou** [comment]
> 
> 不可能在运行中校验，运行中属于事中，要事前就校验处理，所以应该是启动立马校验。 It is impossible to verify during operation. It belongs to the process during operation, and it needs to be verified in advance, so it should be verified immediately after starting.

我不是说在运行中校验，看是否能找到更好的时机，比如项目启动完时。现在创建连接代理时，都还没给我机会初始化脚本，就去检测，那spring datasource 提供的初始化功能， flyway提供的初始化功能都失效了， 或者看能否调整DataSourceProxy这个Bean的构建时机。
