### ISSUE TITLE
start the project with seata，unknown type:�� �t �TCP

### ISSUE THREAD

**Issue by yby1213** [apache/incubator-seata#6885]
start the project find an error
![image](https://github.com/user-attachments/assets/7816c191-0082-4f63-a282-d6a7748f955c)

the error message

**Comment by yby1213** [comment]
Caused by: java.lang.ExceptionInInitializerError: null
	at io.seata.core.rpc.netty.TmNettyRemotingClient.getInstance(TmNettyRemotingClient.java:130) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.core.rpc.netty.TmNettyRemotingClient.getInstance(TmNettyRemotingClient.java:113) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.tm.TMClient.init(TMClient.java:46) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.initClient(GlobalTransactionScanner.java:224) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.spring.annotation.GlobalTransactionScanner.afterPropertiesSet(GlobalTransactionScanner.java:470) ~[seata-all-2.0.0.jar:2.0.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar:5.3.23]
	... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: unknown type:�� t TCP
	at io.seata.core.rpc.TransportProtocolType.getType(TransportProtocolType.java:56) ~[seata-all-2.0.0.jar:2.0.0]
	at io.seata.core.rpc.netty.NettyBaseConfig.<clinit>(NettyBaseConfig.java:115) ~[seata-all-2.0.0.jar:2.0.0]

**Comment by yby1213** [comment]
properties：

**Comment by yby1213** [comment]
#seata
seata.enabled=true
seata.application-id=yy-seata-default
seata.tx-service-group=yy-kernel-seata-group
seata.service.vgroup-mapping.yy-kernel-seata-group=default
seata.service.grouplist.default=localhost:8091
seata.service-name=yy-kernel-seata
seata.registry.type=zk
seata.registry.zk.server-addr=localhost:2181
#seata.registry.address=
seata.config.type=zk
seata.config.zk.server-addr=localhost:2181

**Comment by funky-eyes** [comment]
应该与你配置有关,可能存在的隐藏符号之类的问题,导致type无法匹配.
It should be related to your configuration. There may be problems such as hidden symbols, resulting in type not matching.

**Comment by yby1213** [comment]
seata.enabled=true
seata.application-id=test-seata-default
seata.tx-service-group=my_test_tx_group
seata.enable-auto-data-source-proxy=true
seata.use-jdk-proxy=false
seata.client.rm.async-commit-buffer-limit=1000
seata.client.rm.report-retry-count=5
seata.client.rm.table-meta-check-enable=false
seata.client.rm.report-success-enable=false
seata.client.rm.lock.retry-interval=10
seata.client.rm.lock.retry-times=30
seata.client.rm.lock.retry-policy-branch-rollback-on-conflict=true
seata.client.tm.commit-retry-count=5
seata.client.tm.rollback-retry-count=5
seata.client.undo.data-validation=true
seata.client.undo.log-serialization=jackson
seata.client.undo.log-table=undo_log
seata.log.exceptionRate=100
seata.service.vgroup-mapping.my_test_tx_group=default
seata.service.grouplist.default=127.0.0.1:8091
seata.service.enable-degrade=false
seata.service.disable-global-transaction=false
seata.transport.shutdown.wait=3
seata.transport.thread-factory.boss-thread-prefix=NettyBoss
seata.transport.thread-factory.worker-thread-prefix=NettyServerNIOWorker
seata.transport.thread-factory.server-executor-thread-prefix=NettyServerBizHandler
seata.transport.thread-factory.share-boss-worker=false
seata.transport.thread-factory.client-selector-thread-prefix=NettyClientSelector
seata.transport.thread-factory.client-selector-thread-size=1
seata.transport.thread-factory.client-worker-thread-prefix=NettyClientWorkerThread
seata.transport.thread-factory.worker-thread-size=default
seata.transport.thread-factory.boss-thread-size=1
seata.transport.type=TCP
seata.transport.server=NIO
seata.transport.heartbeat=true
seata.transport.serialization=seata
seata.transport.compressor=none
seata.transport.enable-client-batch-send-request=true
seata.config.type=zk
seata.config.zk.server-addr=127.0.0.1:2181
seata.config.zk.session-timeout=6000
seata.config.zk.connect-timeout=2000
seata.registry.type=zk
seata.registry.zk.server-addr=127.0.0.1:2181
seata.registry.zk.session-timeout=6000
seata.registry.zk.connect-timeout=2000

**Comment by yby1213** [comment]
this is my new configuration,it looks truely

**Comment by funky-eyes** [comment]
你可以提供一个复现该问题的demo?
Can you provide a demo that replicates the problem?

**Comment by yby1213** [comment]
it seems cant

**Comment by funky-eyes** [comment]
因为我这边用相同的配置无法复现，所以可能只是你本地环境，比如字符集有问题导致的。
Because I can't reproduce the issue with the same configuration, it might be specific to your local environment, such as a character set problem.

**Comment by slievrly** [comment]
Delete the configuration seata.transport.type=TCP and restart. There are invisible characters here.
