### ISSUE TITLE
java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by funky-eyes** [apache/incubator-seata#6895]
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
store.mode=file
```
2024-09-29 15:15:02.846 ERROR --- [http-nio-7091-exec-5] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] [log] []: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.ConcurrentModificationException] with root cause
==>
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
	at org.apache.seata.server.storage.SessionConverter.convertBranchSession(SessionConverter.java:218)
	at org.apache.seata.server.storage.SessionConverter.convertGlobalSession(SessionConverter.java:198)
	at org.apache.seata.server.console.impl.file.GlobalSessionFileServiceImpl.query(GlobalSessionFileServiceImpl.java:60)
	at org.apache.seata.server.console.controller.GlobalSessionController.query(GlobalSessionController.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

**Comment by malikrohail** [comment]
hi can i fix this?

**Comment by funky-eyes** [comment]
> hi can i fix this?

of course

**Comment by funky-eyes** [comment]
> hi can i fix this?

Hello @malikrohail , I would like to ask how the progress is so far.

**Comment by psxjoy** [comment]
Hi, @funky-eyes , I noticed this issue for a long time.
I think we can optimize the `convertBranchSession`method by using `synchronized` or  `CopyOnWriteArrayList`.
If my opinion is right, feel free to assign it to me anytime :)

**Comment by vivek092002** [comment]
Hi, I would Like to contribute and make these changes
