### ISSUE TITLE
 org.apache.seata.common.exception.NotSupportYetException: not support sql [insert into a(consignee_location) values(ST_GeomFromText(CONCAT('POINT(', ?, ' ', ?, ')')))

### ISSUE THREAD

**Issue by bruce-pang** [apache/incubator-seata#6941]
### Ⅰ. Issue Description
org.apache.seata.common.exception.NotSupportYetException:notsupportsql[insertinto order(......., consignee_location)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,ST_GeomFromText(CONCAT('POINT(',?,'',?,')'))),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,ST_GeomFromText(CONCAT('POINT(',?,'',?,')'))),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,ST_GeomFromText(CONCAT('POINT(',?,'',?,')')))]

### Ⅱ. Describe what happened

  当我执行批量插入时，如果上述的SQL有批量插入3条以下，程序能完美执行，但是当我将批量插入的数据变为3条及其以上的时候，就会出现title的错误：

```
Just paste your stack trace here!
```
Causedby:org.apache.seata.common.exception.NotSupportYetException:notsupportsql[insert into order(.....consignee_location)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,ST_GeomFromText(CONCAT('POINT(',?,'',?,')'))),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,ST_GeomFromText(CONCAT('POINT(',?,'',?,')'))),(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?,?,?,?,?,?,?,ST_GeomFromText(CONCAT('POINT(',?,'',?,')')))]
	at org.apache.seata.rm.datasource.exec.BaseInsertExecutor.parsePkValuesFromStatement(BaseInsertExecutor.java:217)
	at org.apache.seata.rm.datasource.exec.mysql.MySQLInsertExecutor.getPkValuesByColumn(MySQLInsertExecutor.java:185)
	at org.apache.seata.rm.datasource.exec.mysql.MySQLInsertExecutor.getPkValues(MySQLInsertExecutor.java:90)
	at org.apache.seata.rm.datasource.exec.BaseInsertExecutor.afterImage(BaseInsertExecutor.java:78)
	at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitFalse(AbstractDMLBaseExecutor.java:100)
	at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.lambda$executeAutoCommitTrue$2(AbstractDMLBaseExecutor.java:145)
	at org.apache.seata.rm.datasource.ConnectionProxy$LockRetryPolicy.doRetryOnLockConflict(ConnectionProxy.java:356)
	at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor$LockRetryPolicy.execute(AbstractDMLBaseExecutor.java:188)
	at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.executeAutoCommitTrue(AbstractDMLBaseExecutor.java:144)
	at org.apache.seata.rm.datasource.exec.AbstractDMLBaseExecutor.doExecute(AbstractDMLBaseExecutor.java:83)
	at org.apache.seata.rm.datasource.exec.BaseTransactionalExecutor.execute(BaseTransactionalExecutor.java:127)
	at org.apache.seata.rm.datasource.exec.ExecuteTemplate.execute(ExecuteTemplate.java:168)
	... 253 common frames omitted

### Ⅵ. Environment:

- JDK version: 17
- Seata client/server version:  2.1.0
- Database version: 8.0.30

**Comment by bruce-pang** [comment]
Seata是否提供机制去重写SQL解析器？

**Comment by slievrly** [comment]
> Seata是否提供机制去重写SQL解析器？

AT mode SQL parser is SPI extension, can be customized implementation.
