### ISSUE TITLE
Seata 2.2.0 TCC模式 性能测试崩溃

### ISSUE THREAD

**Issue by timzaak** [apache/incubator-seata#6972]
### Ⅰ. Issue Description
压测 TCC，事务内容不涉及数据库，只是打印日志， Seata Server 会崩溃。

### Ⅱ. Describe what happened

```
org.apache.seata.core.exception.GlobalTransactionException: Could not register branch into global session xid = 192.168.31.146:8091:45617806985154261 status = Rollbacking while expecting Begin
	at org.apache.seata.server.coordinator.AbstractCore.globalSessionStatusCheck(AbstractCore.java:127) ~[classes/:na]
	at org.apache.seata.server.coordinator.AbstractCore.lambda$branchRegister$0(AbstractCore.java:98) ~[classes/:na]
	at org.apache.seata.server.storage.redis.session.RedisSessionManager.lockAndExecute(RedisSessionManager.java:146) ~[classes/:na]
	at org.apache.seata.server.session.SessionHolder.lockAndExecute(SessionHolder.java:358) ~[classes/:na]
	at org.apache.seata.server.coordinator.AbstractCore.branchRegister(AbstractCore.java:97) ~[classes/:na]
	at org.apache.seata.server.coordinator.DefaultCore.branchRegister(DefaultCore.java:107) ~[classes/:na]
	at org.apache.seata.server.coordinator.DefaultCoordinator.doBranchRegister(DefaultCoordinator.java:317) [classes/:na]
	at org.apache.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:184) ~[classes/:na]
	at org.apache.seata.server.AbstractTCInboundHandler$4.execute(AbstractTCInboundHandler.java:179) ~[classes/:na]
	at org.apache.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:127) ~[seata-core-2.2.0.jar:2.2.0]
	at org.apache.seata.server.AbstractTCInboundHandler.handle(AbstractTCInboundHandler.java:179) [classes/:na]
	at org.apache.seata.core.protocol.transaction.BranchRegisterRequest.handle(BranchRegisterRequest.java:136) [seata-core-2.2.0.jar:2.2.0]
	at org.apache.seata.server.coordinator.DefaultCoordinator.onRequest(DefaultCoordinator.java:642) [classes/:na]
	at org.apache.seata.core.rpc.processor.server.ServerOnRequestProcessor.handleRequestsByMergedWarpMessage(ServerOnRequestProcessor.java:288) [seata-core-2.2.0.jar:2.2.0]
	at org.apache.seata.core.rpc.processor.server.ServerOnRequestProcessor.lambda$onRequestMessage$1(ServerOnRequestProcessor.java:178) [seata-core-2.2.0.jar:2.2.0]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[na:1.8.0_342]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) ~[na:1.8.0_342]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_342]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_342]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_342]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[na:1.8.0_342]
<==
```

在出现此日志后，很快崩掉。

### Ⅲ. Describe what you expected to happen
不要崩溃。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

参考：
代码仓库地址：
https://github.com/timzaak/hp 
其中 cloud 目录下使用Seata测试分布式事务， benchmark 目录是性能测试脚本。
在将  cloud 内的三个服务跑起来后，
在benchmark 目录执行：
```sh

sbt 'Gatling/testOnly com.timzaak.cloud.BaseTransactionBenchmark' -Dusers=200 -Drepeat=100

```
环境部署参考：
https://timzaak.github.io/hp/cloud/01_split.html
相关测试运行参考：
https://timzaak.github.io/hp/cloud/02_benchmark.html

### . Environment:

- JDK version(e.g. `java -version`): 17
- Seata client/server version:   2.2.0
- Database version: Postgres 17 （测试内容不涉及数据库）
- OS(e.g. `uname -a`): Docker
- Others:

**Comment by funky-eyes** [comment]
tc的store.mode是db？

**Comment by wt-better** [comment]
‘很快崩掉’，有什么具体表现或者日志吗，看异常应该是事务rollbak后还在注册分支导致的异常

**Comment by timzaak** [comment]
> tc的store.mode是db？

@funky-eyes  store.mode先用了文件，然后用  redis， 都崩溃。 db还没测试。
> ‘很快崩掉’，有什么具体表现或者日志吗，看异常应该是事务rollback后还在注册分支导致的异常

@wt-better 日志就是上述，表现： docker 镜像 down 掉。  

demo  prepare、commit、rollback 代码逻辑：打印个xid日志并返回true。理论上不应该出现 rollback。难道是事务超时导致先出发rollback，再触发 prepare？ 这也不致于崩溃。

补充一下文件索引：
配置文件： https://github.com/timzaak/hp/blob/main/cloud/seata.application.yml 
日志配置： https://github.com/timzaak/hp/blob/main/cloud/seata.logback.xml
事务demo 部分代码（共三个微服务）：  
事务执行方：（两个微服务代码类似）
https://github.com/timzaak/hp/blob/main/cloud/others/src/main/java/com/timzaak/cloud/service/TCCTestImpl.java
事务触发方：
https://github.com/timzaak/hp/blob/dde2c7915c98e95dda1d45d99fedf2341b909e48/cloud/order/src/main/java/com/timzaak/cloud/order/service/TCCTestService.java#L29

2.0.0 ，2.2.0 两个版本都会崩掉。

性能测试截图：<img width="1639" alt="image" src="https://github.com/user-attachments/assets/02c83496-0d17-471d-9454-b9972669deb6">

**Comment by funky-eyes** [comment]
`Could not register branch into global session xid = 192.168.31.146:8091:45617806985154261 status = Rollbacking while expecting Begin`
这个日志说明你的rm 注册到tc时,事务已经决议成回滚了,具体为什么决议成回滚,你应该分析的tm侧的日志是否出现了异常,还有你应该查看是否你的client存在瓶颈,出现了某些异常导致决议成回滚,或者client存在阻塞导致rm注册的时机是滞后的.以及你压测的并发度是多少,tps是多少,是否你的tc配置足够.
如果你压测都放在一台机器上进行,很可能出现了oom killer,导致容器挂掉,先考虑你自己的压测环境是否合理吧

**Comment by timzaak** [comment]
部署在云端测试，测试中未崩溃，性能如下：https://timzaak.github.io/hp/benchmark.html#%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C-1

**Comment by funky-eyes** [comment]
> 部署在云端测试，测试中未崩溃，性能如下：https://timzaak.github.io/hp/benchmark.html#%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C-1

谢谢你的反馈
Thank you for your feedback.

**Comment by funky-eyes** [comment]
你可以再测下关闭防悬挂的性能测试报告吗？server的xmx和xms默认都是2g，这块你有改动过吗？

**Comment by timzaak** [comment]
> 你可以再测下关闭防悬挂的性能测试报告吗？server的xmx和xms默认都是2g，这块你有改动过吗？

这次没有改动参数，因为没有上细粒度监控，以及这次测试的目标只是简单和单体服务进行比对。

防悬挂这块功能还是很有价值的，实际应用中不敢关它，期望能有个 redis 版本的防悬挂。 

这次对于 seata 有价值的测试是 分布式事务基准测试 和  rpc 基准测试，这俩比较着看会相对合理，下单测试涉及业务逻辑和实现方案，对于 Seata TCC 性能参考价值不是很大。

这次的测试，相比于真实的微服务性能测试还是太过单薄，参考意义不是很大。后面有时间，我会再搞一下。
