### ISSUE TITLE
这是bug吗?mysql驱动不存在

### ISSUE THREAD

**Issue by icodegarden** [apache/incubator-seata#6979]
v2.2.0 容器启动报错

Caused by: org.apache.seata.common.exception.StoreException: The driver {com.mysql.jdbc.Driver} cannot be found in the path /lib/jdbc/. Please ensure that the appropriate database driver dependencies are included in the classpath.
	at org.apache.seata.core.store.db.AbstractDataSourceProvider.validate(AbstractDataSourceProvider.java:82)
	at org.apache.seata.core.store.db.AbstractDataSourceProvider.generate(AbstractDataSourceProvider.java:63)
	at org.apache.seata.core.store.db.AbstractDataSourceProvider.init(AbstractDataSourceProvider.java:54)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:707)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:492)
	... 48 more

![image](https://github.com/user-attachments/assets/19a4041a-42b3-4253-850b-44bbe37854eb)

**Comment by funky-eyes** [comment]
2.1开始就不再内置mysql driver，主要原因是license问题，请自行添加相关driver
