### ISSUE TITLE
2.2启动报错./seata-server.sh -h 127.0.0.1 -p 8091 -m db

### ISSUE THREAD

**Issue by zhiguangji2008** [apache/incubator-seata#6997]
14:10:38.663  INFO --- [                     main] [der$InnerEnhancedServiceLoader] [lExtensionDefinition]  [] : Ignore load compatible class io.seata.config.ExtConfigurationProvider, because is not assignable from origin type org.apache.seata.config.ExtConfigurationProvider
14:10:38.762  INFO --- [                     main] [ta.config.ConfigurationFactory] [                load]  [] : load Configuration from :Spring Configuration
14:10:38.769  INFO --- [                     main] [der$InnerEnhancedServiceLoader] [lExtensionDefinition]  [] : Load compatible class io.seata.config.ConfigurationProvider
14:10:38.781  INFO --- [                     main] [onfig.nacos.NacosConfiguration] [tNacosAuthProperties]  [] : Nacos check auth with userName/password.
14:10:39.042  INFO --- [                     main] [seata.server.ServerApplication] [         logStarting]  [] : Starting ServerApplication v2.2.0 using Java 1.8.0_412 on localhost.localdomain with PID 1352747 (/opt/apache-seata-2.2.0-incubating-bin/seata-server/target/seata-server.jar started by root in /opt/apache-seata-2.2.0-incubating-bin/seata-server/bin)
14:10:39.043  INFO --- [                     main] [seata.server.ServerApplication] [ogStartupProfileInfo]  [] : No active profile set, falling back to 1 default profile: "default"
14:10:40.516  INFO --- [                     main] [mbedded.tomcat.TomcatWebServer] [          initialize]  [] : Tomcat initialized with port(s): 7091 (http)
14:10:40.528  INFO --- [                     main] [oyote.http11.Http11NioProtocol] [                 log]  [] : Initializing ProtocolHandler ["http-nio-7091"]
14:10:40.529  INFO --- [                     main] [.catalina.core.StandardService] [                 log]  [] : Starting service [Tomcat]
14:10:40.530  INFO --- [                     main] [e.catalina.core.StandardEngine] [                 log]  [] : Starting Servlet engine: [Apache Tomcat/9.0.90]
14:10:40.607  INFO --- [                     main] [rBase.[Tomcat].[localhost].[/]] [                 log]  [] : Initializing Spring embedded WebApplicationContext
14:10:40.607  INFO --- [                     main] [letWebServerApplicationContext] [ebApplicationContext]  [] : Root WebApplicationContext: initialization completed in 1515 ms
14:10:41.191  INFO --- [                     main] [vlet.WelcomePageHandlerMapping] [              <init>]  [] : Adding welcome page: class path resource [static/index.html]

14:10:41.549  INFO --- [                     main] [oyote.http11.Http11NioProtocol] [                 log]  [] : Starting ProtocolHandler ["http-nio-7091"]
14:10:41.567  INFO --- [                     main] [mbedded.tomcat.TomcatWebServer] [               start]  [] : Tomcat started on port(s): 7091 (http) with context path ''
14:10:41.577  INFO --- [                     main] [seata.server.ServerApplication] [          logStarted]  [] : Started ServerApplication in 3.909 seconds (JVM running for 4.631)
14:10:41.957  INFO --- [                     main] [rver.lock.LockerManagerFactory] [                init]  [] : use lock store mode: db
14:10:41.974 ERROR --- [                     main] [ache.seata.server.ServerRunner] [                 run]  [] : seata server start error: java.lang.IllegalStateException: Extension instance(definition: org.apache.seata.common.loader.ExtensionDefinition@75bd98d9, class: class org.apache.seata.server.coordinator.AbstractCore)  could not be instantiated: null
==>
org.apache.seata.common.loader.EnhancedServiceNotFoundException: java.lang.IllegalStateException: Extension instance(definition: org.apache.seata.common.loader.ExtensionDefinition@75bd98d9, class: class org.apache.seata.server.coordinator.AbstractCore)  could not be instantiated: null
Caused by: java.lang.IllegalStateException: Extension instance(definition: org.apache.seata.common.loader.ExtensionDefinition@75bd98d9, class: class org.apache.seata.server.coordinator.AbstractCore)  could not be instantiated: null
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:495) ~[seata-common-2.2.0.jar:2.2.0]
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:478) ~[seata-common-2.2.0.jar:2.2.0]
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:412) ~[seata-common-2.2.0.jar:2.2.0]
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$600(EnhancedServiceLoader.java:278) ~[seata-common-2.2.0.jar:2.2.0]
        at org.apache.seata.common.loader.EnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:186) ~[seata-common-2.2.0.jar:2.2.0]
        at org.apache.seata.server.coordinator.DefaultCore.<init>(DefaultCore.java:71) ~[classes!/:2.2.0]
        at org.apache.seata.server.coordinator.DefaultCoordinator.<init>(DefaultCoordinator.java:212) ~[classes!/:2.2.0]
        at org.apache.seata.server.coordinator.DefaultCoordinator.getInstance(DefaultCoordinator.java:233) ~[classes!/:2.2.0]
        at org.apache.seata.server.Server.start(Server.java:96) ~[classes!/:2.2.0]
        at org.apache.seata.server.ServerRunner.run(ServerRunner.java:64) ~[classes!/:2.2.0]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) [spring-boot-2.7.18.jar:2.7.18]
        at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:749) [spring-boot-2.7.18.jar:2.7.18]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:1.8.0_412]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:1.8.0_412]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483) ~[na:1.8.0_412]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_412]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:1.8.0_412]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:1.8.0_412]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_412]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[na:1.8.0_412]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744) [spring-boot-2.7.18.jar:2.7.18]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.7.18.jar:2.7.18]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.7.18.jar:2.7.18]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) [spring-boot-2.7.18.jar:2.7.18]
        at org.apache.seata.server.ServerApplication.main(ServerApplication.java:30) ~[classes!/:2.2.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_412]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_412]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_412]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_412]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[seata-server.jar:2.2.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[seata-server.jar:2.2.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[seata-server.jar:2.2.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[seata-server.jar:2.2.0]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_412]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_412]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_412]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_412]
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:701) ~[seata-common-2.2.0.jar:2.2.0]
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:492) ~[seata-common-2.2.0.jar:2.2.0]
        ... 32 common frames omitted
Caused by: org.apache.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : org.apache.seata.server.lock.LockManager caused by java.lang.IllegalStateException: Extension instance(definition: org.apache.seata.common.loader.ExtensionDefinition@8aa7a26d, class: interface org.apache.seata.server.lock.LockManager)  could not be instantiated: the name of service provider for [org.apache.seata.core.store.db.DataSourceProvider] name is null
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:495)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:478)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:453)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:347)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:278)
        at org.apache.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:116)
        at org.apache.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:101)
        at org.apache.seata.server.lock.LockerManagerFactory.init(LockerManagerFactory.java:69)
        at org.apache.seata.server.lock.LockerManagerFactory.init(LockerManagerFactory.java:52)
        at org.apache.seata.server.lock.LockerManagerFactory.getLockManager(LockerManagerFactory.java:47)
        at org.apache.seata.server.coordinator.AbstractCore.<init>(AbstractCore.java:65)
        at org.apache.seata.server.transaction.at.ATCore.<init>(ATCore.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:701)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:492)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:478)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:412)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$600(EnhancedServiceLoader.java:278)
        at org.apache.seata.common.loader.EnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:186)
        at org.apache.seata.server.coordinator.DefaultCore.<init>(DefaultCore.java:71)
        at org.apache.seata.server.coordinator.DefaultCoordinator.<init>(DefaultCoordinator.java:212)
        at org.apache.seata.server.coordinator.DefaultCoordinator.getInstance(DefaultCoordinator.java:233)
        at org.apache.seata.server.Server.start(Server.java:96)
        at org.apache.seata.server.ServerRunner.run(ServerRunner.java:64)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765)
        at org.springframework.boot.SpringApplication.lambda$callRunners$2(SpringApplication.java:749)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
        at org.apache.seata.server.ServerApplication.main(ServerApplication.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [org.apache.seata.core.store.db.DataSourceProvider] name is null
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:448)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:347)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:278)
        at org.apache.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:116)
        at org.apache.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:101)
        at org.apache.seata.server.storage.db.lock.DataBaseLockManager.init(DataBaseLockManager.java:48)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:707)
        at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:492)
        ... 49 more

<==

14:10:41.974  WARN --- [                 Thread-7] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Start destroying common HttpClient
14:10:41.976  WARN --- [                 Thread-7] [mmon.http.HttpClientBeanHolder] [            shutdown]  [] : [HttpClientBeanHolder] Destruction of the end

**Comment by funky-eyes** [comment]
Add configuration `store.db.datasource=druid`

**Comment by zhiguangji2008** [comment]
> Add configuration `store.db.datasource=druid`

谢谢答复，刚刚试了一下，用./seata-server.sh 启动可以  用-h -p -m那个不行，不知道什么原因

**Comment by funky-eyes** [comment]
> > Add configuration `store.db.datasource=druid`
> 
> 谢谢答复，刚刚试了一下，用./seata-server.sh 启动可以 用-h -p -m那个不行，不知道什么原因

你-m设置成了db模式，又没有对应配置，当然不行了

**Comment by zhiguangji2008** [comment]
有DB配置的，就是报上面的错误，不知道原因在哪，尝试过lib/jdbc/放8.0.27驱动包，也不行的
seata:
  config:
    type: nacos
    nacos:
      server-addr: 0.0.0.0:8848
      namespace: seata-dev
      group: SEATA_GROUP
      context-path:
      username: nacos
      password: x
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 0.0.0.0:8848
      namespace: seata-dev
      group: SEATA_GROUP
      cluster: default
      context-path:
      username: nacos
      password: x
  store:
    mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://0.0.0.0:3306/seata?rewriteBatchedStatements=true
      user: root
      password: x
      min-conn: 10
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      vgroup-table: vgroup_table
      query-limit: 1000
      max-wait: 5000

**Comment by funky-eyes** [comment]
nacos里面怎么配置的？

**Comment by Renkai123** [comment]
@zhiguangji2008 配nacos配置的话，他会去读nacos配置。我就简单点删掉读本地了
