### ISSUE TITLE
在k8s集群部署seata，一切正常，但是在物理机重启情况下，有个别微服务在整合seata时，报错vgroupMapping.seata-group configuration item is required，单独重启微服务pod就又正常了

### ISSUE THREAD

**Issue by JsonLYH** [apache/incubator-seata#7041]
2024-12-02 10:59:56.944 [TID:N/A] [timeoutChecker_1_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 10:59:56.944 [TID:N/A] [timeoutChecker_1_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 10:59:57.388 [TID:N/A] [timeoutChecker_2_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 10:59:57.388 [TID:N/A] [timeoutChecker_2_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-7] INFO  c.m.r.LoginRequestInterceptor-请求路径***********************************************http://10.244.94.56:9021/nacos/health/mebay-id
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-6] INFO  c.m.r.LoginRequestInterceptor-请求路径***********************************************http://10.244.94.56:9021/nacos/health/mebay-id
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-6] INFO  c.mebay.controller.HealthController-探测通过，当前容器IP：10.244.94.56
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-7] INFO  c.mebay.controller.HealthController-探测通过，当前容器IP：10.244.94.56
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-7] INFO  c.m.r.LoginRequestInterceptor-请求路径***********************************************http://10.244.94.56:9021/nacos/health/mebay-id
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-6] INFO  c.m.r.LoginRequestInterceptor-请求路径***********************************************http://10.244.94.56:9021/nacos/health/mebay-id
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-6] INFO  c.mebay.controller.HealthController-探测通过，当前容器IP：10.244.94.56
2024-12-02 11:00:05.467 [TID:Ignored_Trace] [http-nio-9021-exec-7] INFO  c.mebay.controller.HealthController-探测通过，当前容器IP：10.244.94.56
2024-12-02 11:00:06.944 [TID:N/A] [timeoutChecker_1_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 11:00:06.944 [TID:N/A] [timeoutChecker_1_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 11:00:07.388 [TID:N/A] [timeoutChecker_2_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-12-02 11:00:07.388 [TID:N/A] [timeoutChecker_2_1] ERROR i.s.c.r.n.NettyClientChannelManager-Failed to get available servers: service.vgroupMapping.seata-group configuration item is required
io.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.seata-group configuration item is required
        at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.lookup(NacosRegistryServiceImpl.java:151)
        at io.seata.core.rpc.netty.NettyClientChannelManager.getAvailServerList(NettyClientChannelManager.java:277)
        at io.seata.core.rpc.netty.NettyClientChannelManager.reconnect(NettyClientChannelManager.java:213)
        at io.seata.core.rpc.netty.AbstractNettyRemotingClient.lambda$init$0(AbstractNettyRemotingClient.java:109)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by funky-eyes** [comment]
nacos中的配置发出来
The configuration in nacos is sent out.
