### ISSUE TITLE
发起全局事务超时报错：io.seata.core.exception.TmTransactionException: RPC timeout 

### ISSUE THREAD

**Issue by gitHubYi** [apache/incubator-seata#7048]
**客户端日志：**
17:00:10.603 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - channel [id: 0x617445bc, L:/10.200.28.13:48236 - R:/10.200.28.15:8091] read idle. 
17:00:10.603 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - will destroy channel:[id: 0x617445bc, L:/10.200.28.13:48236 - R:/10.200.28.15:8091] 
17:00:10.604 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x617445bc, L:/10.200.28.13:48236 - R:/10.200.28.15:8091]) will closed 
17:00:10.604 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091]) will closed 
17:00:10.604 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.NettyClientChannelManager - return to pool, rm channel:[id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091] 
17:00:10.604 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - channel valid false,channel:[id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091] 
17:00:10.604 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - will destroy channel:[id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091] 
17:00:10.604 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091]) will closed 
17:00:10.605 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091]) will closed 
17:00:10.605 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - channel inactive: [id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091] 
17:00:10.605 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - channel valid false,channel:[id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091] 
17:00:10.605 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - will destroy channel:[id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091] 
17:00:10.605 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091]) will closed 
17:00:10.605 [NettyClientSelector_TMROLE_1_1][] INFO  io.seata.core.rpc.netty.AbstractNettyRemotingClient - ChannelHandlerContext(AbstractNettyRemotingClient$ClientHandler#0, [id: 0x617445bc, L:/10.200.28.13:48236 ! R:/10.200.28.15:8091]) will closed 
17:00:15.205 [timeoutChecker_1_1][] INFO  io.seata.core.rpc.netty.NettyClientChannelManager - will connect to 10.200.28.15:8091 
17:00:15.206 [timeoutChecker_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - NettyPool create channel to transactionRole:TMROLE,address:10.200.28.15:8091,msg:< RegisterTMRequest{version='1.8.0', applicationId='scf-client', transactionServiceGroup='scf_tx_group', extraData='ak=null 
digest=scf_tx_group,10.200.28.13,1733216415205 
timestamp=1733216415205 
authVersion=V4 
vgroup=scf_tx_group 
ip=10.200.28.13 
'} > 
17:00:15.215 [timeoutChecker_1_1][] INFO  io.seata.core.rpc.netty.TmNettyRemotingClient - register TM success. client version:1.8.0, server version:1.8.0,channel:[id: 0x5a8b3322, L:/10.200.28.13:57974 - R:/10.200.28.15:8091] 
17:00:15.216 [timeoutChecker_1_1][] INFO  io.seata.core.rpc.netty.NettyPoolableFactory - register success, cost 5 ms, version:1.8.0,role:TMROLE,channel:[id: 0x5a8b3322, L:/10.200.28.13:57974 - R:/10.200.28.15:8091] 
17:00:31.526 [http-nio-8081-exec-52][6fce2aee-d06f-4070-aaf8-21448397cff4] ERROR io.seata.core.rpc.netty.AbstractNettyRemoting - wait response error:null ,cost: 30002 ms,ip:/10.200.28.15:8091,request:GlobalBeginRequest{transactionName='repay_callback', timeout=120000} 
17:00:31.547 [http-nio-8081-exec-52][6fce2aee-d06f-4070-aaf8-21448397cff4] WARN  io.seata.tm.api.DefaultFailureHandlerImpl - Failed to begin transaction.  
io.seata.core.exception.TmTransactionException: RPC timeout 
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:97) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.tm.DefaultTransactionManager.begin(DefaultTransactionManager.java:53) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.tm.api.DefaultGlobalTransaction.begin(DefaultGlobalTransaction.java:113) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.tm.api.TransactionalTemplate.beginTransaction(TransactionalTemplate.java:290) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.tm.api.TransactionalTemplate.execute(TransactionalTemplate.java:123) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.handleGlobalTransaction(GlobalTransactionalInterceptor.java:205) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.spring.annotation.GlobalTransactionalInterceptor.invoke(GlobalTransactionalInterceptor.java:175) ~[seata-all-1.8.0.jar:1.8.0] 
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22] 
	at com.tansun.tb.disbursement.api.impl.DisbursementApiImpl$$EnhancerBySpringCGLIB$$ae6e6d02.updateRepayPayCallTrans(<generated>) ~[tb-disbursement-service-4.3.1-SCF-CXJK-SNAPSHOT.jar:?] 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] 
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] 
	at com.tansun.tb.scf.cptlhrpay.action.CallBackAction.callBack(CallBackAction.java:139) ~[scf-controller-4.3.1-SCF-CXJK-SNAPSHOT.jar:?] 
	at com.tansun.tb.scf.cptlhrpay.action.CallBackAction$$FastClassBySpringCGLIB$$c8309dbc.invoke(<generated>) ~[scf-controller-4.3.1-SCF-CXJK-SNAPSHOT.jar:?] 
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.22.jar:5.3.22] 
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.22.jar:5.3.22] 
	at com.tansun.tb.scf.cptlhrpay.action.CallBackAction$$EnhancerBySpringCGLIB$$1a6a81ce.callBack(<generated>) ~[scf-controller-4.3.1-SCF-CXJK-SNAPSHOT.jar:?] 
	at sun.reflect.GeneratedMethodAccessor2619.invoke(Unknown Source) ~[?:?] 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] 
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] 
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.22.jar:5.3.22] 
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[servlet-api.jar:?] 
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.22.jar:5.3.22] 
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:?] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at com.tansun.tb.common.filter.ParamFilter.doFilter(ParamFilter.java:38) ~[scf-controller-4.3.1-SCF-CXJK-SNAPSHOT.jar:?] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) ~[shiro-core-1.9.1.jar:1.9.1] 
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) ~[shiro-core-1.9.1.jar:1.9.1] 
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) ~[shiro-core-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) ~[shiro-web-1.9.1.jar:1.9.1] 
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.22.jar:5.3.22] 
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.22.jar:5.3.22] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at com.jeedev.msdp.filter.PreventFalsifyFilter.doFilter(PreventFalsifyFilter.java:84) ~[msdp-prevent-falsify-3.0.1-tb-SNAPSHOT.jar:?] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.22.jar:5.3.22] 
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.17.1.jar:2.17.1] 
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:196) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:698) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[catalina.jar:8.5.75] 
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:366) ~[catalina.jar:8.5.75] 
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:639) ~[tomcat-coyote.jar:8.5.75] 
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-coyote.jar:8.5.75] 
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:847) ~[tomcat-coyote.jar:8.5.75] 
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1680) ~[tomcat-coyote.jar:8.5.75] 
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-coyote.jar:8.5.75] 
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:8.5.75] 
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:8.5.75] 
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.75] 
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] 
Caused by: java.util.concurrent.TimeoutException: null ,cost: 30002 ms 
	at io.seata.core.protocol.MessageFuture.get(MessageFuture.java:65) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.core.rpc.netty.AbstractNettyRemoting.sendSync(AbstractNettyRemoting.java:199) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.core.rpc.netty.AbstractNettyRemotingClient.sendSyncRequest(AbstractNettyRemotingClient.java:187) ~[seata-all-1.8.0.jar:1.8.0] 
	at io.seata.tm.DefaultTransactionManager.syncCall(DefaultTransactionManager.java:95) ~[seata-all-1.8.0.jar:1.8.0] 
	... 95 more 

**服务端日志：**
2024-12-03 17:00:01.531  INFO --- [batchLoggerPrint_1_1] [io.seata.core.rpc.processor.server.BatchLogHandler] [run] []: receive msg[single]: GlobalBeginRequest{transactionName='repay_callback', timeout=120000}, clientIp: 10.200.28.13, vgroup: scf_tx_group
2024-12-03 17:00:01.535  INFO --- [ServerHandlerThread_1_39_500] [io.seata.server.coordinator.DefaultCoordinator] [doGlobalBegin] [10.200.28.15:8091:8512379241854878904]: Begin new global transaction applicationId: scf-client,transactionServiceGroup: scf_tx_group, transactionName: repay_callback,timeout:120000,xid:10.200.28.15:8091:8512379241854878904
2024-12-03 17:00:10.605  INFO --- [NettyServerNIOWorker_1_9_16] [io.seata.core.rpc.netty.AbstractNettyRemotingServer] [handleDisconnect] []: 10.200.28.13:48236 to server channel inactive.
2024-12-03 17:00:10.806  INFO --- [NettyServerNIOWorker_1_9_16] [io.seata.core.rpc.netty.AbstractNettyRemotingServer] [handleDisconnect] []: remove channel:[id: 0xea2bbf5c, L:/10.200.28.15:8091 ! R:/10.200.28.13:48236]context:RpcContext{applicationId='scf-client', transactionServiceGroup='scf_tx_group', clientId='scf-client:10.200.28.13:48236', channel=[id: 0xea2bbf5c, L:/10.200.28.15:8091 ! R:/10.200.28.13:48236], resourceSets=null}
2024-12-03 17:00:10.727 ERROR --- [ServerHandlerThread_1_39_500] [io.seata.core.rpc.netty.AbstractNettyRemoting] [lambda$processMessage$2] [10.200.28.15:8091:8512379241854878904]: 0104
==>
java.lang.RuntimeException: channel is error.
	at io.seata.core.rpc.netty.AbstractNettyRemotingServer.sendAsyncResponse(AbstractNettyRemotingServer.java:106)
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.onRequestMessage(ServerOnRequestProcessor.java:207)
	at io.seata.core.rpc.processor.server.ServerOnRequestProcessor.process(ServerOnRequestProcessor.java:122)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:281)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
<==

2024-12-03 17:00:15.215  INFO --- [NettyServerNIOWorker_1_15_16] [io.seata.core.rpc.processor.server.RegTmProcessor] [onRegTmMessage] []: TM register success,message:RegisterTMRequest{version='1.8.0', applicationId='scf-client', transactionServiceGroup='scf_tx_group', extraData='ak=null
digest=scf_tx_group,10.200.28.13,1733216415205
timestamp=1733216415205
authVersion=V4
vgroup=scf_tx_group
ip=10.200.28.13
'},channel:[id: 0x8a2b12ad, L:/10.200.28.15:8091 - R:/10.200.28.13:57974],client version:1.8.0
2024-12-03 17:02:01.773  INFO --- [RetryRollbacking_1_1] [io.seata.server.coordinator.DefaultCore] [doGlobalRollback] [10.200.28.15:8091:8512379241854878904]: Rollback global transaction successfully, xid = 10.200.28.15:8091:8512379241854878904.

看日志分析应该是发起全局事务的时候网络通道已经是非活跃状态了，服务端断掉通道导致报错超时，请问下是什么原因导致，如果避免这种问题

- JDK version(e.g. `java -version`): 1.8
- Seata client/server version:  1.8.0/1.8.0
- Database version: mysql5.7

**Comment by slievrly** [comment]
It seems that the request and response are not on the same channel.

**Comment by tonglsh** [comment]
<img width="1519" alt="Image" src="https://github.com/user-attachments/assets/5d7662b2-6881-4ddd-bfa1-bf3191a8ff70" /> meet the same situation, only restart seata server can resolve. What caused it？
