### ISSUE TITLE
 AT mode don't support the dbtype: mysql

### ISSUE THREAD

**Issue by zuihou** [apache/incubator-seata#7076]
seata 2.0.0 升级到2.2.0 后，报错： 

```
Caused by: java.lang.IllegalStateException: AT mode don't support the dbtype: mysql
	at org.apache.seata.rm.datasource.DataSourceProxy.checkUndoLogTableExist(DataSourceProxy.java:172) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.rm.datasource.DataSourceProxy.init(DataSourceProxy.java:115) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:101) ~[seata-all-2.2.0.jar:2.2.0]
	at org.apache.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:86) ~[seata-all-2.2.0.jar:2.2.0]
	at io.seata.rm.datasource.DataSourceProxy.<init>(DataSourceProxy.java:39) ~[seata-all-2.2.0.jar:2.2.0]
	at com.baomidou.dynamic.datasource.creator.DefaultDataSourceCreator.wrapDataSource(DefaultDataSourceCreator.java:148) ~[dynamic-datasource-spring-4.3.1.jar:na]
	at com.baomidou.dynamic.datasource.creator.DefaultDataSourceCreator.createDataSource(DefaultDataSourceCreator.java:102) ~[dynamic-datasource-spring-4.3.1.jar:na]
	at com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider.createDataSourceMap(AbstractDataSourceProvider.java:53) ~[dynamic-datasource-spring-4.3.1.jar:na]
	at com.baomidou.dynamic.datasource.provider.YmlDynamicDataSourceProvider.loadDataSources(YmlDynamicDataSourceProvider.java:53) ~[dynamic-datasource-spring-4.3.1.jar:na]
	at com.baomidou.dynamic.datasource.DynamicRoutingDataSource.afterPropertiesSet(DynamicRoutingDataSource.java:229) ~[dynamic-datasource-spring-4.3.1.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-6.1.15.jar:6.1.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802) ~[spring-beans-6.1.15.jar:6.1.15]
	... 98 common frames omitted
```

**Comment by zuihou** [comment]
<img width="1472" alt="image" src="https://github.com/user-attachments/assets/4ba5092d-c35a-4b82-85b9-b529381e7945" />

**Comment by zuihou** [comment]
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/34f3228c-ab1a-41e2-85f2-091b6392f229" />
 有这个类，但 `Class<?> clazz = Class.forName(className, true, loader);` 方法加载不到该类

**Comment by funky-eyes** [comment]
你可能存在io seata与apache seata的依赖冲突

**Comment by zuihou** [comment]
<img width="673" alt="image" src="https://github.com/user-attachments/assets/4481403a-fc67-45a1-ae37-ec6f8540c9bb" />
项目里面只有一个版本的seata

**Comment by funky-eyes** [comment]
mvn dependency:tree
执行后看下结果

**Comment by zuihou** [comment]
问题解决了，打扰了。确实依赖问题。


```
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>springseata</artifactId>
<version>2023.0.1.2</version>
            <exclusions>
                <exclusion>
<!-- 该版本需要排除 io.seata ， 我全局替换成：             <groupId>org.apache.seata</groupId> 了 -->
                    <groupId>io.seata</groupId>
                    <artifactId>seata-all</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.seata</groupId>
                    <artifactId>seata-spring-boot-starter</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.seata</groupId>
            <artifactId>seata-all</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.seata</groupId>
            <artifactId>seata-spring-boot-starter</artifactId>
        </dependency>
```
